/**********************************************************************************************************************
Table Name: [dwhcda].[lnc_fct_Rep_Production_Receipts]
Description: This is a Fact Table for Warehouse Production Receipts

Data Type: Fact Data

Original Project: JBT Production Planning & Scheduling
Developer: Mohammed Majid
Date: 10/08/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [dwhcda].[lnc_fct_Rep_Production_Receipts];

CREATE TABLE [dwhcda].[lnc_fct_Rep_Production_Receipts]
(
	[acti] [varchar](255) NULL,
	[adin] [varchar](22) NULL,
	[ardt] [datetime] NULL,
	[arej] [int] NULL,
	[arej_kw] [varchar](255) NULL,
	[bgxc] [int] NULL,
	[bgxc_kw] [varchar](255) NULL,
	[blck] [int] NULL,
	[blck_kw] [varchar](255) NULL,
	[casi] [varchar](3) NULL,
	[cdck] [int] NULL,
	[cdck_kw] [varchar](255) NULL,
	[cdcr] [int] NULL,
	[cdcr_kw] [varchar](255) NULL,
	[circ] [varchar](255) NULL,
	[clot] [varchar](20) NULL,
	[cmnf] [varchar](6) NULL,
	[cmpl] [int] NULL,
	[cmpl_kw] [varchar](255) NULL,
	[compnr] [varchar](10) NOT NULL,
	[conf] [int] NULL,
	[conf_kw] [varchar](255) NULL,
	[cpro] [varchar](255) NULL,
	[cwar] [varchar](6) NULL,
	[deleted] [varchar](10) NULL,
	[disp] [int] NULL,
	[disp_kw] [varchar](255) NULL,
	[dmse] [int] NULL,
	[dmse_kw] [varchar](255) NULL,
	[dslo] [varchar](10) NULL,
	[effn] [int] NULL,
	[exhu] [varchar](25) NULL,
	[exrr] [varchar](20) NULL,
	[fire] [int] NULL,
	[fire_kw] [varchar](255) NULL,
	[huid] [varchar](25) NULL,
	[hupr] [int] NULL,
	[hupr_kw] [varchar](255) NULL,
	[idat] [datetime] NULL,
	[insp] [int] NULL,
	[insp_kw] [varchar](255) NULL,
	[item] [varchar](47) NULL,
	[itxt] [int] NULL,
	[ksig] [varchar](20) NULL,
	[zload] [varchar](9) NULL,
	[logn] [varchar](16) NULL,
	[lsta] [int] NULL,
	[lsta_kw] [varchar](255) NULL,
	[ltbp] [varchar](30) NULL,
	[mpnr] [varchar](35) NULL,
	[oorg] [int] NULL,
	[oorg_kw] [varchar](255) NULL,
	[orno] [varchar](9) NULL,
	[oset] [int] NULL,
	[pkdf] [varchar](6) NULL,
	[pmsk] [varchar](20) NULL,
	[pono] [int] NULL,
	[psno] [varchar](255) NULL,
	[psqr] [float] NULL,
	[psqu] [float] NULL,
	[psun] [varchar](3) NULL,
	[qadi] [float] NULL,
	[qadv] [float] NULL,
	[qapr] [float] NULL,
	[qdes] [float] NULL,
	[qdms] [float] NULL,
	[qpui] [float] NULL,
	[qput] [float] NULL,
	[qrcr] [float] NULL,
	[qrec] [float] NULL,
	[qrej] [float] NULL,
	[qrsc] [float] NULL,
	[rcln] [int] NOT NULL,
	[rclo] [varchar](10) NULL,
	[rcno] [varchar](9) NOT NULL,
	[rcun] [varchar](3) NULL,
	[refe] [varchar](255) NULL,
	[resn] [varchar](6) NULL,
	[revi] [varchar](6) NULL,
	[rtcf] [varchar](19) NULL,
	[seqn] [int] NULL,
	[serl] [varchar](30) NULL,
	[sfbp] [varchar](9) NULL,
	[shdt] [datetime] NULL,
	[shid] [varchar](9) NULL,
	[shpm] [varchar](9) NULL,
	[shsq] [int] NULL,
	[spcn] [varchar](22) NULL,
	[tcst] [int] NULL,
	[tcst_kw] [varchar](255) NULL,
	[ztimestamp] [datetime] NULL,
	[tlot] [varchar](20) NULL,
	[trdt] [datetime] NULL,
	[tsrl] [varchar](30) NULL,
	[txtn] [int] NULL,
	[wght] [float] NULL,
	[wtun] [varchar](3) NULL,
	[file_name] [varchar](100) NOT NULL,
	[dwh_load_time] [datetime] NOT NULL,
	[carr] [varchar](3) NULL,
	[cdec] [varchar](3) NULL,
	[hsta] [int] NULL,
	[hsta_kw] [varchar](255) NULL,
	[ittp] [int] NULL,
	[ittp_kw] [varchar](255) NULL,
	[odat] [datetime] NULL,
	[sfsi] [varchar](9) NULL,
	[sfad] [varchar](9) NULL,
	[stad] [varchar](9) NULL,
	[wdep] [varchar](6) NULL,
	[clsd] [int] NULL,
	[clsd_kw] [varchar](255) NULL,
	[cwoc] [varchar](6) NULL,
	[prfd] [datetime] NULL,
	[prmd] [varchar](9) NULL,
	[prsd] [datetime] NULL,
	[prsh] [varchar](9) NULL,
	[qrdr] [float] NULL,
	[sdtp] [int] NULL,
	[sdtp_kw] [varchar](255) NULL,
	[site] [varchar](9) NULL,
	[prod_rec_fct_key] [varchar](50) NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (Prod_Rec_fct_key)
)
GO


