CREATE TABLE [replncss].[CDW fct AP Open Item Cube]
(
	[Amt] [float] NULL,
	[Amt In Inv Curr] [float] NULL,
	[Balance Anticipated] [float] NULL,
	[Balance] [float] NULL,
	[Balance In HC] [float] NULL,
	[Total Balance] [float] NULL,
	[Tax Amt In HC] [float] NULL,
	[Dwh Load Time] [datetime] NOT NULL,
	[AP Open Item fct key] [varchar](50) NOT NULL,
	[Category] [varchar](6) NULL,
	[Category Type] [int] NULL,
	[Category Type Desc] [varchar](255) NULL,
	[Category Description] [varchar](255) NULL,
	[Responsible Employee] [varchar](9) NULL,
	[Responsible Office] [varchar](6) NULL,
	[Category Text] [int] NULL,
	[Payment Terms] [varchar](3) NULL,
	[Payment Terms Company] [varchar](255) NULL,
	[Payment Period] [int] NULL,
	[Payment Period Type Key] [int] NULL,
	[Payment Period Type] [varchar](255) NULL,
	[Shift in Due Dt Tolerance] [int] NULL,
	[Discount Amount Tolerance] [float] NULL,
	[Discount Percentage Tolerance] [float] NULL,
	[Discount Period Tolerance] [int] NULL,
	[Tax Code Desc] [varchar](255) NULL,
	[Pay-to Address Code] [varchar](9) NULL,
	[Pay-to Country] [varchar](50) NULL,
	[Pay-to Country Name] [varchar](255) NULL,
	[Pay-to BP Name] [varchar](255) NULL,
	[Pay-to State/Province] [varchar](50) NULL,
	[Pay-to City Name] [varchar](255) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [AP Open Item fct key] )
)
GO

CREATE TABLE [replncss].[CDW fct Ap Purchase Order Lines Cube]
(
	[Purchase Acknowledgment] [varchar](2) NULL,
	[Warehouse Address] [varchar](9) NULL,
	[Tax Country] [varchar](3) NULL,
	[Cancellation In Process] [int] NULL,
	[Cancellation In Process Desc] [varchar](255) NULL,
	[Canceled] [int] NULL,
	[Canceled Desc] [varchar](255) NULL,
	[Contract Ignored] [int] NULL,
	[Contract Ignored Desc] [varchar](255) NULL,
	[Company Number] [varchar](10) NOT NULL,
	[Contract] [varchar](9) NULL,
	[Contract Position] [int] NULL,
	[Project] [varchar](9) NULL,
	[Product Variant] [int] NULL,
	[Carrier Binding] [int] NULL,
	[Carrier Binding Desc] [varchar](255) NULL,
	[Reason For Rejection] [varchar](6) NULL,
	[Item Cross Reference] [int] NULL,
	[Item Cross Reference Desc] [varchar](255) NULL,
	[Change Type] [varchar](6) NULL,
	[Receipt Amt] [float] NULL,
	[Confirmed Receipt Date] [datetime] NULL,
	[Order Confirmation Date] [datetime] NULL,
	[General Ledger] [varchar](135) NULL,
	[Inv Date] [datetime] NULL,
	[Invoice] [varchar](9) NULL,
	[Item] [varchar](47) NULL,
	[Cc: Total Landed Cost] [float] NULL,
	[Order Amt] [float] NULL,
	[Order Date] [datetime] NULL,
	[Order Line Type] [int] NULL,
	[Order Line Type Desc] [varchar](255) NULL,
	[Buy-From BP] [varchar](9) NULL,
	[Return Ownership] [int] NULL,
	[Return Ownership Desc] [varchar](255) NULL,
	[Line] [int] NOT NULL,
	[Purchase Type] [varchar](6) NULL,
	[Received Qty] [float] NULL,
	[Invd Qty] [float] NULL,
	[Rejected Qty] [float] NULL,
	[Ordered Qty] [float] NULL,
	[Receipt Number] [varchar](9) NULL,
	[Standard Description] [int] NULL,
	[Standard Description Desc] [varchar](255) NULL,
	[Ship-From Contact] [varchar](9) NULL,
	[Ship-From Site] [varchar](9) NULL,
	[Ship-From Warehouse] [varchar](6) NULL,
	[Site] [varchar](9) NULL,
	[Specification] [varchar](22) NULL,
	[Inv Status] [int] NULL,
	[Inv Status Desc] [varchar](255) NULL,
	[Subcontracted] [int] NULL,
	[Subcontracted Desc] [varchar](255) NULL,
	[Target Price] [float] NULL,
	[Target Price Book] [varchar](9) NULL,
	[Target Price Book Line] [int] NULL,
	[Vendor Rating] [int] NULL,
	[Dwh Load time] [datetime] NOT NULL,
	[PU Order Lines fct key] [varchar](255) NULL,
	[Vendor Rating Desc] [varchar](255) NULL,
	[Tax Classification Desc] [varchar](255) NULL,
	[Max W/Tax %] [float] NULL,
	[SCT Allowed] [int] NULL,
	[SCT Allowed Falg] [varchar](255) NULL,
	[WIT Allowed] [int] NULL,
	[WIT Allowed Flag] [varchar](255) NULL,
	[Delivery Terms Desc] [varchar](255) NULL,
	[Carrier/LSP Desc] [varchar](255) NULL,
	[Buy-from Business Partner] [varchar](9) NULL,
	[Transport Category] [int] NULL,
	[Transport Category Desc] [varchar](255) NULL,
	[Payment Terms] [varchar](3) NULL,
	[Payment Terms Company] [varchar](255) NULL,
	[Payment Period] [int] NULL,
	[Payment Period Type Key] [int] NULL,
	[Payment Period Type] [varchar](255) NULL,
	[Shift in Due Dt Tolerance] [int] NULL,
	[Discount Amount Tolerance] [float] NULL,
	[Discount Percentage Tolerance] [float] NULL,
	[Discount Period Tolerance] [int] NULL,
	[Change Reason Desc] [varchar](255) NULL,
	[Tax Code Desc] [varchar](255) NULL,
	[Warehouse Desc] [varchar](255) NULL,
	[Warehouse Address Code] [varchar](9) NULL,
	[Financial Company] [int] NULL,
	[Enterprise unit of Wh] [varchar](6) NULL,
	[Inventory Mgt Business Partner] [varchar](9) NULL,
	[External Site] [int] NULL,
	[External Site Flag] [varchar](255) NULL,
	[Blocked for Inbound] [int] NULL,
	[Blocked for Inbound Desc] [varchar](255) NULL,
	[Blocked for Outbound] [int] NULL,
	[Blocked for Outbound Desc] [varchar](255) NULL,
	[Items Desc] [varchar](255) NULL,
	[Item Group] [varchar](6) NULL,
	[Product Class] [varchar](6) NULL,
	[Product Line] [varchar](6) NULL,
	[Item Signal] [varchar](3) NULL,
	[Country of Origin] [varchar](3) NULL,
	[Product Type] [varchar](3) NULL,
	[Inventory Unit] [varchar](3) NULL,
	[Serialized] [int] NULL,
	[Default Supply Source] [int] NULL,
	[PoT Passage Desc] [varchar](255) NULL,
	[PoT Passage Spec Key] [int] NULL,
	[PoT Passage Spec] [varchar](255) NULL,
	[Ship-from Address Code] [varchar](9) NULL,
	[Ship-from Country] [varchar](50) NULL,
	[Ship-from Country Name] [varchar](255) NULL,
	[Ship-from BP Name] [varchar](255) NULL,
	[Ship-from State/Province] [varchar](50) NULL,
	[Ship-from City Name] [varchar](255) NULL,
	[Pur Office Description] [varchar](255) NULL,
	[Pur Office Warehouse] [varchar](6) NULL,
	[Pur Office Site] [varchar](9) NULL,
	[Product Line Levels] [int] NULL,
	[Product Line First Level] [varchar](100) NULL,
	[Product Line Second Level] [varchar](100) NULL,
	[Product Line Third Level] [varchar](100) NULL,
	[Ship-from Region] [varchar](50) NULL,
	[Ship-from Sub Region] [varchar](100) NULL,
	[Sold-to Region] [varchar](50) NULL,
	[Sold-to Sub Region] [varchar](100) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [PU Order Lines fct key] )
)
GO

CREATE TABLE [replncss].[CDW fct AP Purchase Order Line History Cube]
(
	[Purchase Acknowledgment] [varchar](2) NULL,
	[Order Line Disc Amt] [float] NULL,
	[Amt] [float] NULL,
	[Approved] [int] NULL,
	[Approved Desc] [varchar](255) NULL,
	[Tax Classification] [varchar](12) NULL,
	[Cost Component] [varchar](8) NULL,
	[Purchase Office] [varchar](6) NULL,
	[Carrier/Lsp] [varchar](3) NULL,
	[Record Type] [int] NOT NULL,
	[Record Type Desc] [varchar](255) NULL,
	[Lot] [varchar](20) NULL,
	[Canceled] [int] NULL,
	[Canceled Desc] [varchar](255) NULL,
	[Company Number] [varchar](10) NOT NULL,
	[Contract] [varchar](9) NULL,
	[Project] [varchar](9) NULL,
	[Carrier Binding] [int] NULL,
	[Carrier Binding Desc] [varchar](255) NULL,
	[Change Reason] [varchar](6) NULL,
	[Reason For Rejection] [varchar](6) NULL,
	[Element] [varchar](16) NULL,
	[Change Type] [varchar](6) NULL,
	[Purchase Unit] [varchar](3) NULL,
	[Tax Code] [varchar](9) NULL,
	[Warehouse] [varchar](6) NULL,
	[Receipt Amt] [float] NULL,
	[Number Of Deliveries Done] [int] NULL,
	[Planned Receipt Date] [datetime] NULL,
	[Current Planned Receipt Date] [datetime] NULL,
	[Confirmed Receipt Date] [datetime] NULL,
	[Changed Receipt Date] [datetime] NULL,
	[Actual Receipt Date] [datetime] NULL,
	[Order Confirmation Date] [datetime] NULL,
	[Final Receipt] [int] NULL,
	[Final Receipt Desc] [varchar](255) NULL,
	[General Ledger] [varchar](135) NULL,
	[History Action] [int] NULL,
	[History Action Desc] [varchar](255) NULL,
	[Inv Amt] [float] NULL,
	[Inv Date] [datetime] NULL,
	[Invoice] [varchar](9) NULL,
	[Item] [varchar](47) NULL,
	[Planned Load Date] [datetime] NULL,
	[Lot Selection] [int] NULL,
	[Order Amt] [float] NULL,
	[Order Date] [datetime] NULL,
	[Original Order] [varchar](9) NULL,
	[Original Line] [int] NULL,
	[Purchase Order] [varchar](9) NOT NULL,
	[Original Seq] [int] NULL,
	[Buy-From BP] [varchar](9) NULL,
	[Purchase Order Line] [int] NOT NULL,
	[Price] [float] NULL,
	[Purchase Type] [varchar](6) NULL,
	[Approved Qty] [float] NULL,
	[Backorder Qty] [float] NULL,
	[Potential Backorder Qty] [float] NULL,
	[Received Qty] [float] NULL,
	[Invd Qty] [float] NULL,
	[Quantity] [float] NULL,
	[Rejected Qty] [float] NULL,
	[Shipped Qty] [float] NULL,
	[Ordered Qty] [float] NULL,
	[Rept Line] [int] NULL,
	[Sales Schedule Type] [int] NULL,
	[Sales Schedule Type Desc] [varchar](255) NULL,
	[Ship-From Address] [varchar](9) NULL,
	[Ship-From BP] [varchar](9) NULL,
	[Ship-From Contact] [varchar](9) NULL,
	[Ship-From Site] [varchar](9) NULL,
	[Ship-From Warehouse] [varchar](6) NULL,
	[Site] [varchar](9) NULL,
	[Sales Order / Schedule] [varchar](9) NULL,
	[Spon Line] [int] NULL,
	[SequenceNumber] [int] NOT NULL,
	[Seq] [int] NULL,
	[Status] [int] NULL,
	[Status Desc] [varchar](255) NULL,
	[Inv Status] [int] NULL,
	[Inv Status Desc] [varchar](255) NULL,
	[Trn Date] [datetime] NOT NULL,
	[Dwh Load Time] [datetime] NOT NULL,
	[PU Order Line His fct key] [varchar](255) NOT NULL,
	[Tax Classification Desc] [varchar](255) NULL,
	[Max W/Tax %] [float] NULL,
	[SCT Allowed] [int] NULL,
	[SCT Allowed Falg] [varchar](255) NULL,
	[WIT Allowed] [int] NULL,
	[WIT Allowed Flag] [varchar](255) NULL,
	[Pur Office Description] [varchar](255) NULL,
	[Pur Office Warehouse] [varchar](6) NULL,
	[Pur Office Site] [varchar](9) NULL,
	[Delivery Terms Desc] [varchar](255) NULL,
	[Payment Terms] [varchar](3) NULL,
	[Payment Terms Company] [varchar](255) NULL,
	[Payment Period] [int] NULL,
	[Payment Period Type Key] [int] NULL,
	[Payment Period Type] [varchar](255) NULL,
	[Shift in Due Dt Tolerance] [int] NULL,
	[Discount Amount Tolerance] [float] NULL,
	[Discount Percentage Tolerance] [float] NULL,
	[Discount Period Tolerance] [int] NULL,
	[Change Reason Desc] [varchar](255) NULL,
	[Tax Code Desc] [varchar](255) NULL,
	[Warehouse Desc] [varchar](255) NULL,
	[Warehouse Address Code] [varchar](9) NULL,
	[Financial Company] [int] NULL,
	[Enterprise unit of Wh] [varchar](6) NULL,
	[Inventory Mgt Business Partner] [varchar](9) NULL,
	[WH External Site] [int] NULL,
	[WH External Site Flag] [varchar](255) NULL,
	[Blocked for Hnbound] [int] NULL,
	[Blocked for Inbound Desc] [varchar](255) NULL,
	[Blocked for Outbound] [int] NULL,
	[Blocked for Outbound Desc] [varchar](255) NULL,
	[Items Desc] [varchar](255) NULL,
	[Item Group] [varchar](6) NULL,
	[Product Class] [varchar](6) NULL,
	[Product Line] [varchar](6) NULL,
	[Item Signal] [varchar](3) NULL,
	[Country of Origin] [varchar](3) NULL,
	[Product Type] [varchar](3) NULL,
	[Inventory Unit] [varchar](3) NULL,
	[Serialized] [int] NULL,
	[Default Supply Source] [int] NULL,
	[Buy-from Address Code] [varchar](9) NULL,
	[Buy-from Country] [varchar](50) NULL,
	[Buy-from Country Name] [varchar](255) NULL,
	[Buy-from BP Name] [varchar](255) NULL,
	[Buy-from State/Province] [varchar](50) NULL,
	[Buy-from City Name] [varchar](255) NULL,
	[PoT Passage Desc] [varchar](255) NULL,
	[PoT Passage Spec Key] [int] NULL,
	[PoT Passage Spec] [varchar](255) NULL,
	[Ship-from Address Code] [varchar](9) NULL,
	[Ship-from Country] [varchar](50) NULL,
	[Ship-from Country Name] [varchar](255) NULL,
	[Ship-from BP Name] [varchar](255) NULL,
	[Ship-from State/Province] [varchar](50) NULL,
	[Ship-from City Name] [varchar](255) NULL,
	[Address] [varchar](9) NULL,
	[Sites Description] [varchar](255) NULL,
	[Parent Site] [varchar](9) NULL,
	[Site Category] [varchar](9) NULL,
	[Site Status] [int] NULL,
	[Text] [int] NULL,
	[External Site] [int] NULL,
	[Product Line Levels] [int] NULL,
	[Product Line First Level] [varchar](100) NULL,
	[Product Line Second Level] [varchar](100) NULL,
	[Product Line Third Level] [varchar](100) NULL,
	[Buy-from Region] [varchar](50) NULL,
	[Buy-from Sub Region] [varchar](100) NULL,
	[Ship-from Region] [varchar](50) NULL,
	[Ship-from Sub Region] [varchar](100) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [PU Order Line His fct key] )
)
GO

CREATE TABLE [replncss].[CDW fct AP Pur Pay Recpt for Orders and Sch Cube]
(
	[Order Line Discount Amount] [float] NULL,
	[Order Discount Amount] [float] NULL,
	[Contract Purchase Office] [varchar](6) NULL,
	[Contract Ignored] [int] NULL,
	[Contract Ignored Desc] [varchar](255) NULL,
	[Company number] [varchar](10) NOT NULL,
	[Contract] [varchar](9) NULL,
	[Contract Position] [int] NULL,
	[Contract Sequence] [int] NULL,
	[Purchase Price Unit] [varchar](3) NULL,
	[Conversion Factor Price to Inventory Unit] [float] NULL,
	[Determining] [int] NULL,
	[Determining Desc] [varchar](255) NULL,
	[Eligible] [int] NULL,
	[Eligible Desc] [varchar](255) NULL,
	[Finance Transaction Date] [datetime] NULL,
	[Invoiced Amount] [float] NULL,
	[Invoice Date] [datetime] NULL,
	[Invoice Number] [varchar](9) NULL,
	[Original Payable] [int] NULL,
	[Purchase Order/Schedule] [varchar](9) NOT NULL,
	[Payable Amount in Order Currency] [float] NULL,
	[Price Matrix] [varchar](9) NULL,
	[Price Matrix Sequence] [int] NULL,
	[Line Position] [int] NOT NULL,
	[Price Origin] [int] NULL,
	[Price Origin Desc] [varchar](255) NULL,
	[Price] [float] NULL,
	[Processed] [int] NULL,
	[Processed Desc] [varchar](255) NULL,
	[Price Stage] [varchar](3) NULL,
	[Payable Receipt Sequence] [int] NOT NULL,
	[Payable Receipt Type] [int] NULL,
	[Payable Receipt Type Desc] [varchar](255) NULL,
	[Invoiced Quantity] [float] NULL,
	[Payable Quantity in Inventory Unit] [float] NULL,
	[Retro-Active] [int] NULL,
	[Retro-Active Desc] [varchar](255) NULL,
	[Reason for Amount Change] [int] NULL,
	[Reason for Amount Change Desc] [varchar](255) NULL,
	[Receipt Sequence] [int] NOT NULL,
	[Line Sequence] [int] NOT NULL,
	[Update Status of Actual Purchase Costs] [int] NULL,
	[Update Status of Actual Purchase Costs Desc] [varchar](255) NULL,
	[Invoicing Status] [int] NULL,
	[Invoicing Status Desc] [varchar](255) NULL,
	[Purchase Schedule Type] [int] NULL,
	[Purchase Schedule Type Desc] [varchar](255) NULL,
	[Usage Log Date] [datetime] NULL,
	[Usage Date] [datetime] NULL,
	[Dwh Load Time] [datetime] NOT NULL,
	[Pur Pay fct key] [varchar](100) NULL,
	[Pur Office Description] [varchar](255) NULL,
	[Pur Office Warehouse] [varchar](6) NULL,
	[Pur Office Site] [varchar](9) NULL,
	[Com Address Code] [varchar](9) NULL,
	[Com Line of Business] [varchar](6) NULL,
	[Com Country] [varchar](3) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Pur Pay fct key] )
)
GO
