/**********************************************************************************************************************
Table Name: [acq101].[dst_tfacp500]
Description: This is a DST table for Accounts Payable Open Items

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tfacp500];

CREATE TABLE [acq101].[dst_tfacp500] 
(
	adcd [varchar](3) NULL,
	adif [varchar](255) NULL,
	adty [int] NULL,
	adty_kw [varchar](255) NULL,
	afpy [int] NULL,
	afpy_kw [varchar](255) NULL,
	amnt [float] NULL,
	amth_1 [float] NULL,
	amth_2 [float] NULL,
	amth_3 [float] NULL,
	amti [float] NULL,
	appr [int] NULL,
	appr_kw [varchar](255) NULL,
	autm [int] NULL,
	autm_kw [varchar](255) NULL,
	baca_1 [float] NULL,
	baca_2 [float] NULL,
	baca_3 [float] NULL,
	baco [float] NULL,
	bahc_1 [float] NULL,
	bahc_2 [float] NULL,
	bahc_3 [float] NULL,
	bala [float] NULL,
	balc [float] NULL,
	balh_1 [float] NULL,
	balh_2 [float] NULL,
	balh_3 [float] NULL,
	bank [varchar](3) NULL,
	basi [float] NULL,
	bdat [varchar](10) NULL,
	bdsp [int] NULL,
	bdsp_kw [varchar](255) NULL,
	bkrn [varchar](27) NULL,
	blac [int] NULL,
	blac_kw [varchar](255) NULL,
	bloc [varchar](3) NULL,
	brat [float] NULL,
	bref [varchar](3) NULL,
	btno [int] NULL,
	bust [int] NULL,
	bust_kw [varchar](255) NULL,
	ccrs [varchar](3) NULL,
	ccur [varchar](3) NULL,
	cdam_1 [float] NULL,
	cdam_2 [float] NULL,
	cdam_3 [float] NULL,
	cfrs [varchar](6) NULL,
	clus [varchar](9) NULL,
	compnr [varchar](10) NOT NULL,
	copy [int] NULL,
	copy_kw [varchar](255) NULL,
	cpay [varchar](3) NULL,
	cvat [varchar](9) NULL,
	dapr [int] NULL,
	dc1a [float] NULL,
	dc1h_1 [float] NULL,
	dc1h_2 [float] NULL,
	dc1h_3 [float] NULL,
	dc1i [float] NULL,
	dc2a [float] NULL,
	dc2h_1 [float] NULL,
	dc2h_2 [float] NULL,
	dc2h_3 [float] NULL,
	dc2i [float] NULL,
	dc3a [float] NULL,
	dc3h_1 [float] NULL,
	dc3h_2 [float] NULL,
	dc3h_3 [float] NULL,
	dc3i [float] NULL,
	deleted [varchar](10) NULL,
	did1 [varchar](10) NULL,
	did2 [varchar](10) NULL,
	did3 [varchar](10) NULL,
	dim1 [varchar](9) NULL,
	dim2 [varchar](9) NULL,
	dim3 [varchar](9) NULL,
	dim4 [varchar](9) NULL,
	dim5 [varchar](9) NULL,
	dim6 [varchar](9) NULL,
	dim7 [varchar](9) NULL,
	dim8 [varchar](9) NULL,
	dim9 [varchar](9) NULL,
	dm10 [varchar](9) NULL,
	dm11 [varchar](9) NULL,
	dm12 [varchar](9) NULL,
	doca [int] NULL,
	docd [varchar](10) NULL,
	dued [varchar](10) NULL,
	edtp [int] NULL,
	edtp_kw [varchar](255) NULL,
	fcom [int] NOT NULL,
	fisu [varchar](3) NULL,
	flpd [int] NULL,
	flpd_kw [varchar](255) NULL,
	iadr [varchar](9) NULL,
	icls [int] NULL,
	icls_kw [varchar](255) NULL,
	idmr [varchar](36) NULL,
	ifbp [varchar](9) NULL,
	ifbp_ref_compnr [varchar](10) NULL,
	ildp [int] NULL,
	ildp_kw [varchar](255) NULL,
	irdt [varchar](10) NULL,
	isup [varchar](255) NULL,
	ityp [int] NULL,
	ityp_kw [varchar](255) NULL,
	lapa [float] NULL,
	laph_1 [float] NULL,
	laph_2 [float] NULL,
	laph_3 [float] NULL,
	lapi [float] NULL,
	leac [varchar](12) NULL,
	line [int] NOT NULL,
	link [float] NULL,
	liqd [varchar](10) NULL,
	zload [varchar](9) NULL,
	loco [int] NULL,
	lpdt [varchar](10) NULL,
	lvat [int] NULL,
	lvat_kw [varchar](255) NULL,
	mane [int] NULL,
	mane_kw [varchar](255) NULL,
	msts [int] NULL,
	msts_kw [varchar](255) NULL,
	ninv [int] NOT NULL,
	oinv [int] NULL,
	optb [varchar](9) NULL,
	optb_ref_compnr [varchar](10) NULL,
	orno [varchar](9) NULL,
	osch [int] NULL,
	osup [varchar](255) NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	otyp [varchar](3) NULL,
	pada [float] NULL,
	padh_1 [float] NULL,
	padh_2 [float] NULL,
	padh_3 [float] NULL,
	padi [float] NULL,
	papr [int] NULL,
	papr_kw [varchar](255) NULL,
	paya [varchar](3) NULL,
	paym [varchar](3) NULL,
	pdat [varchar](10) NULL,
	pdif [float] NULL,
	pdoc [varchar](15) NULL,
	pfre [int] NULL,
	pfre_kw [varchar](255) NULL,
	post [int] NULL,
	prin [int] NULL,
	prin_kw [varchar](255) NULL,
	prod [int] NULL,
	ptbp [varchar](9) NULL,
	ptbp_ref_compnr [varchar](10) NULL,
	ptyp [varchar](6) NULL,
	pysh [int] NULL,
	pysh_kw [varchar](255) NULL,
	rade [int] NULL,
	rade_kw [varchar](255) NULL,
	ragr [varchar](16) NULL,
	ratd [datetime] NULL,
	rate_1 [float] NULL,
	rate_2 [float] NULL,
	rate_3 [float] NULL,
	ratf_1 [int] NULL,
	ratf_2 [int] NULL,
	ratf_3 [int] NULL,
	rcom [int] NULL,
	rcpt [int] NULL,
	rcpt_kw [varchar](255) NULL,
	reas [varchar](3) NULL,
	refr [varchar](255) NULL,
	retr [varchar](6) NULL,
	retr_ref_compnr [varchar](10) NULL,
	rinv [varchar](9) NULL,
	rtyp [varchar](3) NULL,
	schn [int] NULL,
	sequencenumber [int] NULL,
	sgdd [int] NULL,
	sgdd_kw [varchar](255) NULL,
	sgtp [int] NULL,
	sgtp_kw [varchar](255) NULL,
	shpi [varchar](9) NULL,
	shpm [varchar](255) NULL,
	stap [int] NULL,
	stap_kw [varchar](255) NULL,
	stat [int] NULL,
	stat_kw [varchar](255) NULL,
	step [int] NULL,
	step_kw [varchar](255) NULL,
	subc [int] NULL,
	subc_kw [varchar](255) NULL,
	svah_1 [float] NULL,
	svah_2 [float] NULL,
	svah_3 [float] NULL,
	svam [float] NULL,
	tapr [varchar](3) NULL,
	tbrl [float] NULL,
	tcns [int] NULL,
	tcns_kw [varchar](255) NULL,
	tcur [varchar](3) NULL,
	tcur_ref_compnr [varchar](10) NULL,
	text [int] NULL,
	text_ref_compnr [varchar](10) NULL,
	ztimestamp [datetime] NULL,
	tnpn [varchar](9) NULL,
	toba [float] NULL,
	tore_1 [float] NULL,
	tore_2 [float] NULL,
	tore_3 [float] NULL,
	tpay [int] NULL,
	tpay_kw [varchar](255) NULL,
	ttyp [varchar](3) NOT NULL,
	txdt [varchar](10) NULL,
	txtb [int] NULL,
	txtb_ref_compnr [varchar](10) NULL,
	typa [varchar](3) NULL,
	zuser [varchar](16) NULL,
	username [varchar](8) NULL,
	vata [float] NULL,
	vatc [varchar](3) NULL,
	vath_1 [float] NULL,
	vath_2 [float] NULL,
	vath_3 [float] NULL,
	vati [float] NULL,
	vatp [int] NULL,
	vaty [int] NULL,
	vrsm [varchar](10) NULL,
	whti [int] NULL,
	whti_kw [varchar](255) NULL,
	wtph_1 [float] NULL,
	wtph_2 [float] NULL,
	wtph_3 [float] NULL,
	wtpi [float] NULL,
	zyear [int] NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (line)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur400]
Description: This is a DST table for Accounts Payable Purchase Orders Header

Data Type: Dimension Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur400];

CREATE TABLE [acq101].[dst_tdpur400] 
(
	adin [varchar](22) NULL,
	akcd [varchar](2) NULL,
	akcd_ref_compnr [varchar](10) NULL,
	bgrb [int] NULL,
	bgrb_kw [varchar](255) NULL,
	bgrq [int] NULL,
	bgrq_kw [varchar](255) NULL,
	bpcl [varchar](12) NULL,
	bpcl_ref_compnr [varchar](10) NULL,
	bppr [varchar](9) NULL,
	bppr_ref_compnr [varchar](10) NULL,
	bptx [varchar](9) NULL,
	bptx_ref_compnr [varchar](10) NULL,
	cadr [varchar](9) NULL,
	cadr_ref_compnr [varchar](10) NULL,
	cbrn [varchar](6) NULL,
	cbrn_ref_compnr [varchar](10) NULL,
	ccon [varchar](9) NULL,
	ccon_ref_compnr [varchar](10) NULL,
	ccrs [varchar](3) NULL,
	ccrs_ref_compnr [varchar](10) NULL,
	ccty [varchar](3) NULL,
	ccur [varchar](3) NULL,
	ccur_ref_compnr [varchar](10) NULL,
	cdec [varchar](3) NULL,
	cdec_ref_compnr [varchar](10) NULL,
	cfrw [varchar](3) NULL,
	cfrw_ref_compnr [varchar](10) NULL,
	chrq [int] NULL,
	chrq_kw [varchar](255) NULL,
	cofc [varchar](6) NULL,
	cofc_ref_compnr [varchar](10) NULL,
	comm [int] NULL,
	comm_kw [varchar](255) NULL,
	compnr [varchar](10) NOT NULL,
	corg [int] NULL,
	corg_kw [varchar](255) NULL,
	cosn [varchar](8) NULL,
	cotp [varchar](3) NULL,
	cotp_ref_compnr [varchar](10) NULL,
	cpay [varchar](3) NULL,
	cpay_ref_compnr [varchar](10) NULL,
	cplp [varchar](3) NULL,
	cplp_ref_compnr [varchar](10) NULL,
	crby [varchar](16) NULL,
	crcd [varchar](6) NULL,
	crcd_ref_compnr [varchar](10) NULL,
	crcl [int] NULL,
	crcl_kw [varchar](255) NULL,
	crdt [datetime] NULL,
	creg [varchar](3) NULL,
	creg_ref_compnr [varchar](10) NULL,
	crht [int] NULL,
	crht_ref_compnr [varchar](10) NULL,
	crin [int] NULL,
	crin_kw [varchar](255) NULL,
	cror [int] NULL,
	cror_kw [varchar](255) NULL,
	crrq [int] NULL,
	crrq_kw [varchar](255) NULL,
	ctcd [varchar](6) NULL,
	ctcd_ref_compnr [varchar](10) NULL,
	ctrj [varchar](5) NULL,
	ctrj_ref_compnr [varchar](10) NULL,
	cvyn [int] NULL,
	cvyn_kw [varchar](255) NULL,
	cwar [varchar](6) NULL,
	cwar_ref_compnr [varchar](10) NULL,
	ddat [datetime] NULL,
	ddtc [datetime] NULL,
	deleted [varchar](10) NULL,
	egen [int] NULL,
	egen_kw [varchar](255) NULL,
	etpc [int] NULL,
	etpc_kw [varchar](255) NULL,
	fdpt [varchar](6) NULL,
	fdpt_ref_compnr [varchar](10) NULL,
	hdst [int] NULL,
	hdst_kw [varchar](255) NULL,
	hism [int] NULL,
	hism_kw [varchar](255) NULL,
	hisp [int] NULL,
	hisp_kw [varchar](255) NULL,
	iafc [int] NULL,
	iafc_kw [varchar](255) NULL,
	iebp [int] NULL,
	iebp_kw [varchar](255) NULL,
	ifad [varchar](9) NULL,
	ifad_ref_compnr [varchar](10) NULL,
	ifbp [varchar](9) NULL,
	ifbp_ref_compnr [varchar](10) NULL,
	ifcn [varchar](9) NULL,
	ifcn_ref_compnr [varchar](10) NULL,
	lccl [varchar](12) NULL,
	lccl_ref_compnr [varchar](10) NULL,
	lcrq [int] NULL,
	lcrq_kw [varchar](255) NULL,
	mcfr [int] NULL,
	mcfr_kw [varchar](255) NULL,
	oamt [float] NULL,
	odat [datetime] NULL,
	odis [float] NULL,
	odno [varchar](9) NULL,
	odty [int] NULL,
	odty_kw [varchar](255) NULL,
	opor [varchar](9) NULL,
	orno [varchar](9) NOT NULL,
	orno_cosn_ref_compnr [varchar](10) NULL,
	otad [varchar](9) NULL,
	otad_ref_compnr [varchar](10) NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	otcn [varchar](9) NULL,
	otcn_ref_compnr [varchar](10) NULL,
	paft [int] NULL,
	paft_kw [varchar](255) NULL,
	plnr [varchar](9) NULL,
	plnr_ref_compnr [varchar](10) NULL,
	prno [varchar](9) NULL,
	prno_ref_compnr [varchar](10) NULL,
	ptad [varchar](9) NULL,
	ptad_ref_compnr [varchar](10) NULL,
	ptbp [varchar](9) NULL,
	ptbp_ref_compnr [varchar](10) NULL,
	ptcn [varchar](9) NULL,
	ptcn_ref_compnr [varchar](10) NULL,
	ptpa [varchar](9) NULL,
	ptpa_ref_compnr [varchar](10) NULL,
	ragr [varchar](16) NULL,
	ratc_dtwc [float] NULL,
	ratc_lclc [float] NULL,
	ratc_rfrc [float] NULL,
	ratc_rpc1 [float] NULL,
	ratc_rpc2 [float] NULL,
	ratd [datetime] NULL,
	ratf_1 [int] NULL,
	ratf_2 [int] NULL,
	ratf_3 [int] NULL,
	ratp_1 [float] NULL,
	ratp_2 [float] NULL,
	ratp_3 [float] NULL,
	ratt [varchar](3) NULL,
	ratt_ref_compnr [varchar](10) NULL,
	raur [int] NULL,
	raur_kw [varchar](255) NULL,
	refa [varchar](255) NULL,
	refb [varchar](255) NULL,
	retr [varchar](6) NULL,
	retr_ref_compnr [varchar](10) NULL,
	revn [int] NULL,
	sbim [int] NULL,
	sbim_kw [varchar](255) NULL,
	sbmt [varchar](3) NULL,
	sbmt_ref_compnr [varchar](10) NULL,
	sequencenumber [int] NULL,
	sfad [varchar](9) NULL,
	sfad_ref_compnr [varchar](10) NULL,
	sfbp [varchar](9) NULL,
	sfbp_ref_compnr [varchar](10) NULL,
	sfcn [varchar](9) NULL,
	sfcn_ref_compnr [varchar](10) NULL,
	site [varchar](9) NULL,
	site_ref_compnr [varchar](10) NULL,
	sorn [varchar](255) NULL,
	ztimestamp [datetime] NULL,
	txta [int] NULL,
	txta_ref_compnr [varchar](10) NULL,
	txtb [int] NULL,
	txtb_ref_compnr [varchar](10) NULL,
	username [varchar](8) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (orno)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur401]
Description: This is a DST table for Accounts Payable Purchase Order Lines

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur401];

CREATE TABLE [acq101].[dst_tdpur401] 
(
	acti [varchar](255) NULL,
	adin [varchar](22) NULL,
	akcd [varchar](2) NULL,
	akcd_ref_compnr [varchar](10) NULL,
	amld [float] NULL,
	amod [float] NULL,
	appr [int] NULL,
	appr_kw [varchar](255) NULL,
	bgrb [int] NULL,
	bgrb_kw [varchar](255) NULL,
	bgrq [int] NULL,
	bgrq_kw [varchar](255) NULL,
	bgxc [int] NULL,
	bgxc_kw [varchar](255) NULL,
	bkyn [int] NULL,
	bkyn_kw [varchar](255) NULL,
	bpcl [varchar](12) NULL,
	bpcl_ref_compnr [varchar](10) NULL,
	bptc [varchar](3) NULL,
	bptc_ref_compnr [varchar](10) NULL,
	btsp [int] NULL,
	btsp_kw [varchar](255) NULL,
	btx1 [int] NULL,
	btx1_ref_compnr [varchar](10) NULL,
	btx2 [int] NULL,
	btx2_ref_compnr [varchar](10) NULL,
	cact [varchar](16) NULL,
	cadr [varchar](9) NULL,
	cadr_ref_compnr [varchar](10) NULL,
	casi [varchar](3) NULL,
	casi_ref_compnr [varchar](10) NULL,
	ccco [varchar](8) NULL,
	ccco_ref_compnr [varchar](10) NULL,
	ccof [varchar](6) NULL,
	ccty [varchar](3) NULL,
	ccty_cvat_ref_compnr [varchar](10) NULL,
	ccty_ref_compnr [varchar](10) NULL,
	cdec [varchar](3) NULL,
	cdec_ref_compnr [varchar](10) NULL,
	cdf_jbtd [varchar](255) NULL,
	cdis_1 [varchar](3) NULL,
	cdis_10 [varchar](3) NULL,
	cdis_11 [varchar](3) NULL,
	cdis_2 [varchar](3) NULL,
	cdis_3 [varchar](3) NULL,
	cdis_4 [varchar](3) NULL,
	cdis_5 [varchar](3) NULL,
	cdis_6 [varchar](3) NULL,
	cdis_7 [varchar](3) NULL,
	cdis_8 [varchar](3) NULL,
	cdis_9 [varchar](3) NULL,
	ceno [varchar](24) NULL,
	cfrw [varchar](3) NULL,
	cfrw_ref_compnr [varchar](10) NULL,
	citt [varchar](3) NULL,
	citt_ref_compnr [varchar](10) NULL,
	clip [int] NULL,
	clip_kw [varchar](255) NULL,
	clot [varchar](20) NULL,
	clyn [int] NULL,
	clyn_kw [varchar](255) NULL,
	cmnf [varchar](6) NULL,
	cmnf_ref_compnr [varchar](10) NULL,
	cncd [varchar](6) NULL,
	cnig [int] NULL,
	cnig_kw [varchar](255) NULL,
	comm [int] NULL,
	comm_kw [varchar](255) NULL,
	compnr [varchar](10) NOT NULL,
	cono [varchar](9) NULL,
	coop_1 [float] NULL,
	coop_2 [float] NULL,
	coop_3 [float] NULL,
	coop_trnc [float] NULL,
	copr_1 [float] NULL,
	copr_2 [float] NULL,
	copr_3 [float] NULL,
	copr_trnc [float] NULL,
	corg [int] NULL,
	corg_kw [varchar](255) NULL,
	cosn [varchar](8) NULL,
	cpay [varchar](3) NULL,
	cpay_ref_compnr [varchar](10) NULL,
	cpcl [varchar](6) NULL,
	cpcp [varchar](8) NULL,
	cpcp_ref_compnr [varchar](10) NULL,
	cpln [varchar](6) NULL,
	cpon [int] NULL,
	cprj [varchar](9) NULL,
	cprj_ref_compnr [varchar](10) NULL,
	cpva [int] NULL,
	crbn [int] NULL,
	crbn_kw [varchar](255) NULL,
	crcd [varchar](6) NULL,
	crcd_ref_compnr [varchar](10) NULL,
	crej [varchar](6) NULL,
	crej_ref_compnr [varchar](10) NULL,
	crit [varchar](255) NULL,
	crrf [int] NULL,
	crrf_kw [varchar](255) NULL,
	csgp [varchar](6) NULL,
	cspa [varchar](16) NULL,
	csqn [int] NULL,
	cstl [varchar](4) NULL,
	ctcd [varchar](6) NULL,
	ctcd_ref_compnr [varchar](10) NULL,
	ctrj [varchar](5) NULL,
	ctrj_ref_compnr [varchar](10) NULL,
	cubp [varchar](3) NULL,
	cubp_ref_compnr [varchar](10) NULL,
	cupp [varchar](3) NULL,
	cupp_ref_compnr [varchar](10) NULL,
	cuqp [varchar](3) NULL,
	cuqp_ref_compnr [varchar](10) NULL,
	cuva [float] NULL,
	cvat [varchar](9) NULL,
	cvbp [float] NULL,
	cvpp [float] NULL,
	cvqp [float] NULL,
	cwar [varchar](6) NULL,
	cwar_ref_compnr [varchar](10) NULL,
	damt [float] NULL,
	ddon [int] NULL,
	ddta [datetime] NULL,
	ddtb [datetime] NULL,
	ddtc [datetime] NULL,
	ddtd [datetime] NULL,
	ddte [datetime] NULL,
	ddtf [datetime] NULL,
	deleted [varchar](10) NULL,
	dino [varchar](255) NULL,
	disc_1 [float] NULL,
	disc_10 [float] NULL,
	disc_11 [float] NULL,
	disc_2 [float] NULL,
	disc_3 [float] NULL,
	disc_4 [float] NULL,
	disc_5 [float] NULL,
	disc_6 [float] NULL,
	disc_7 [float] NULL,
	disc_8 [float] NULL,
	disc_9 [float] NULL,
	dmde_1 [varchar](9) NULL,
	dmde_10 [varchar](9) NULL,
	dmde_11 [varchar](9) NULL,
	dmde_2 [varchar](9) NULL,
	dmde_3 [varchar](9) NULL,
	dmde_4 [varchar](9) NULL,
	dmde_5 [varchar](9) NULL,
	dmde_6 [varchar](9) NULL,
	dmde_7 [varchar](9) NULL,
	dmde_8 [varchar](9) NULL,
	dmde_9 [varchar](9) NULL,
	dmse_1 [int] NULL,
	dmse_10 [int] NULL,
	dmse_11 [int] NULL,
	dmse_2 [int] NULL,
	dmse_3 [int] NULL,
	dmse_4 [int] NULL,
	dmse_5 [int] NULL,
	dmse_6 [int] NULL,
	dmse_7 [int] NULL,
	dmse_8 [int] NULL,
	dmse_9 [int] NULL,
	dmth_1 [int] NULL,
	dmth_10 [int] NULL,
	dmth_11 [int] NULL,
	dmth_2 [int] NULL,
	dmth_3 [int] NULL,
	dmth_4 [int] NULL,
	dmth_5 [int] NULL,
	dmth_6 [int] NULL,
	dmth_7 [int] NULL,
	dmth_8 [int] NULL,
	dmth_9 [int] NULL,
	dmth_kw_1 [varchar](255) NULL,
	dmth_kw_10 [varchar](255) NULL,
	dmth_kw_11 [varchar](255) NULL,
	dmth_kw_2 [varchar](255) NULL,
	dmth_kw_3 [varchar](255) NULL,
	dmth_kw_4 [varchar](255) NULL,
	dmth_kw_5 [varchar](255) NULL,
	dmth_kw_6 [varchar](255) NULL,
	dmth_kw_7 [varchar](255) NULL,
	dmth_kw_8 [varchar](255) NULL,
	dmth_kw_9 [varchar](255) NULL,
	dmty_1 [int] NULL,
	dmty_10 [int] NULL,
	dmty_11 [int] NULL,
	dmty_2 [int] NULL,
	dmty_3 [int] NULL,
	dmty_4 [int] NULL,
	dmty_5 [int] NULL,
	dmty_6 [int] NULL,
	dmty_7 [int] NULL,
	dmty_8 [int] NULL,
	dmty_9 [int] NULL,
	dmty_kw_1 [varchar](255) NULL,
	dmty_kw_10 [varchar](255) NULL,
	dmty_kw_11 [varchar](255) NULL,
	dmty_kw_2 [varchar](255) NULL,
	dmty_kw_3 [varchar](255) NULL,
	dmty_kw_4 [varchar](255) NULL,
	dmty_kw_5 [varchar](255) NULL,
	dmty_kw_6 [varchar](255) NULL,
	dmty_kw_7 [varchar](255) NULL,
	dmty_kw_8 [varchar](255) NULL,
	dmty_kw_9 [varchar](255) NULL,
	dorg_1 [int] NULL,
	dorg_10 [int] NULL,
	dorg_11 [int] NULL,
	dorg_2 [int] NULL,
	dorg_3 [int] NULL,
	dorg_4 [int] NULL,
	dorg_5 [int] NULL,
	dorg_6 [int] NULL,
	dorg_7 [int] NULL,
	dorg_8 [int] NULL,
	dorg_9 [int] NULL,
	dorg_kw_1 [varchar](255) NULL,
	dorg_kw_10 [varchar](255) NULL,
	dorg_kw_11 [varchar](255) NULL,
	dorg_kw_2 [varchar](255) NULL,
	dorg_kw_3 [varchar](255) NULL,
	dorg_kw_4 [varchar](255) NULL,
	dorg_kw_5 [varchar](255) NULL,
	dorg_kw_6 [varchar](255) NULL,
	dorg_kw_7 [varchar](255) NULL,
	dorg_kw_8 [varchar](255) NULL,
	dorg_kw_9 [varchar](255) NULL,
	dtrm [int] NULL,
	dtrm_kw [varchar](255) NULL,
	effn [int] NULL,
	effn_ref_compnr [varchar](10) NULL,
	elgb [int] NULL,
	elgb_kw [varchar](255) NULL,
	etpc [int] NULL,
	etpc_kw [varchar](255) NULL,
	exmt [int] NULL,
	exmt_kw [varchar](255) NULL,
	fire [int] NULL,
	fire_kw [varchar](255) NULL,
	gefo [int] NULL,
	gefo_kw [varchar](255) NULL,
	glco [varchar](135) NULL,
	iamt [float] NULL,
	invd [datetime] NULL,
	invn [varchar](9) NULL,
	issp [int] NULL,
	issp_kw [varchar](255) NULL,
	item [varchar](47) NULL,
	item_ref_compnr [varchar](10) NULL,
	lcam_trnc [float] NULL,
	lccl [varchar](12) NULL,
	lccl_ref_compnr [varchar](10) NULL,
	lcrq [int] NULL,
	lcrq_kw [varchar](255) NULL,
	ldam_1 [float] NULL,
	ldam_10 [float] NULL,
	ldam_11 [float] NULL,
	ldam_2 [float] NULL,
	ldam_3 [float] NULL,
	ldam_4 [float] NULL,
	ldam_5 [float] NULL,
	ldam_6 [float] NULL,
	ldam_7 [float] NULL,
	ldam_8 [float] NULL,
	ldam_9 [float] NULL,
	ldat [datetime] NULL,
	leng [float] NULL,
	lsel [int] NULL,
	lsel_kw [varchar](255) NULL,
	lseq [int] NULL,
	mitm [varchar](255) NULL,
	mpnr [varchar](35) NULL,
	mpnr_cmnf_ref_compnr [varchar](10) NULL,
	mpsn [varchar](22) NULL,
	mpsn_ref_compnr [varchar](10) NULL,
	oamt [float] NULL,
	odat [datetime] NULL,
	oltp [int] NULL,
	oltp_kw [varchar](255) NULL,
	orno [varchar](9) NOT NULL,
	orno_cosn_ref_compnr [varchar](10) NULL,
	orno_ref_compnr [varchar](10) NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	ownr [varchar](9) NULL,
	ownr_ref_compnr [varchar](10) NULL,
	owns [int] NULL,
	owns_kw [varchar](255) NULL,
	paft [int] NULL,
	paft_kw [varchar](255) NULL,
	paya [varchar](3) NULL,
	paya_ref_compnr [varchar](10) NULL,
	pegd [int] NULL,
	pegd_kw [varchar](255) NULL,
	pmde [varchar](9) NULL,
	pmnd [int] NULL,
	pmnd_kw [varchar](255) NULL,
	pmni [int] NULL,
	pmni_kw [varchar](255) NULL,
	pmnt [int] NULL,
	pmnt_kw [varchar](255) NULL,
	pmse [int] NULL,
	pmsk [varchar](20) NULL,
	pono [int] NOT NULL,
	porg [int] NULL,
	porg_kw [varchar](255) NULL,
	pric [float] NULL,
	prsg [varchar](3) NULL,
	prsg_ref_compnr [varchar](10) NULL,
	pseq [int] NULL,
	ptpa [varchar](9) NULL,
	ptpa_ref_compnr [varchar](10) NULL,
	ptpe [varchar](6) NULL,
	ptpe_ref_compnr [varchar](10) NULL,
	qbbc [float] NULL,
	qbbc_buar [float] NULL,
	qbbc_buln [float] NULL,
	qbbc_bupc [float] NULL,
	qbbc_butm [float] NULL,
	qbbc_buvl [float] NULL,
	qbbc_buwg [float] NULL,
	qbbc_invu [float] NULL,
	qbbc_trnu [float] NULL,
	qiap [float] NULL,
	qiap_buar [float] NULL,
	qiap_buln [float] NULL,
	qiap_bupc [float] NULL,
	qiap_butm [float] NULL,
	qiap_buvl [float] NULL,
	qiap_buwg [float] NULL,
	qiap_trnu [float] NULL,
	qibo [float] NULL,
	qibo_buar [float] NULL,
	qibo_buln [float] NULL,
	qibo_bupc [float] NULL,
	qibo_butm [float] NULL,
	qibo_buvl [float] NULL,
	qibo_buwg [float] NULL,
	qibo_invu [float] NULL,
	qibo_trnu [float] NULL,
	qibp [float] NULL,
	qidl [float] NULL,
	qidl_buar [float] NULL,
	qidl_buln [float] NULL,
	qidl_bupc [float] NULL,
	qidl_butm [float] NULL,
	qidl_buvl [float] NULL,
	qidl_buwg [float] NULL,
	qidl_trnu [float] NULL,
	qiiv [float] NULL,
	qiiv_buar [float] NULL,
	qiiv_buln [float] NULL,
	qiiv_bupc [float] NULL,
	qiiv_butm [float] NULL,
	qiiv_buvl [float] NULL,
	qiiv_buwg [float] NULL,
	qiiv_trnu [float] NULL,
	qips [float] NULL,
	qirj [float] NULL,
	qirj_buar [float] NULL,
	qirj_buln [float] NULL,
	qirj_bupc [float] NULL,
	qirj_butm [float] NULL,
	qirj_buvl [float] NULL,
	qirj_buwg [float] NULL,
	qirj_trnu [float] NULL,
	qoor [float] NULL,
	qoor_buar [float] NULL,
	qoor_buln [float] NULL,
	qoor_bupc [float] NULL,
	qoor_butm [float] NULL,
	qoor_buvl [float] NULL,
	qoor_buwg [float] NULL,
	qoor_invu [float] NULL,
	qual [int] NULL,
	qual_kw [varchar](255) NULL,
	rcno [varchar](9) NULL,
	rcod [varchar](6) NULL,
	rcod_ref_compnr [varchar](10) NULL,
	rdta [datetime] NULL,
	revi [varchar](6) NULL,
	rseq [int] NULL,
	sbim [int] NULL,
	sbim_kw [varchar](255) NULL,
	sbmt [varchar](3) NULL,
	sbmt_ref_compnr [varchar](10) NULL,
	sdsc [int] NULL,
	sdsc_kw [varchar](255) NULL,
	sequencenumber [int] NULL,
	serl [varchar](30) NULL,
	serv [varchar](3) NULL,
	serv_ref_compnr [varchar](10) NULL,
	sfad [varchar](9) NULL,
	sfad_ref_compnr [varchar](10) NULL,
	sfbp [varchar](9) NULL,
	sfbp_ref_compnr [varchar](10) NULL,
	sfcn [varchar](9) NULL,
	sfcn_ref_compnr [varchar](10) NULL,
	sfsi [varchar](9) NULL,
	sfsi_ref_compnr [varchar](10) NULL,
	sfwh [varchar](6) NULL,
	site [varchar](9) NULL,
	site_ref_compnr [varchar](10) NULL,
	spcn [varchar](22) NULL,
	sqnb [int] NOT NULL,
	stdc [float] NULL,
	stsc [int] NULL,
	stsc_kw [varchar](255) NULL,
	stsd [int] NULL,
	stsd_kw [varchar](255) NULL,
	subc [int] NULL,
	subc_kw [varchar](255) NULL,
	tapr [float] NULL,
	taxp [int] NULL,
	taxp_kw [varchar](255) NULL,
	thic [float] NULL,
	ztimestamp [datetime] NULL,
	tpbk [varchar](9) NULL,
	tpbk_ref_compnr [varchar](10) NULL,
	tpbk_tpbl_ref_compnr [varchar](10) NULL,
	tpbl [int] NULL,
	txta [int] NULL,
	txta_ref_compnr [varchar](10) NULL,
	username [varchar](8) NULL,
	vryn [int] NULL,
	vryn_kw [varchar](255) NULL,
	widt [float] NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (pono)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur451]
Description: This is a DST table for Accounts Payable Purchase Order Line History

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur451];

CREATE TABLE [acq101].[dst_tdpur451] 
(
	acti [varchar](255) NULL,
	adin [varchar](22) NULL,
	akcd [varchar](2) NULL,
	akcd_ref_compnr [varchar](10) NULL,
	amld [float] NULL,
	amod [float] NULL,
	amta [float] NULL,
	appr [int] NULL,
	appr_kw [varchar](255) NULL,
	asno [varchar](255) NULL,
	bgrb [int] NULL,
	bgrb_kw [varchar](255) NULL,
	bgrq [int] NULL,
	bgrq_kw [varchar](255) NULL,
	bgxc [int] NULL,
	bgxc_kw [varchar](255) NULL,
	bkyn [int] NULL,
	bkyn_kw [varchar](255) NULL,
	bpcl [varchar](12) NULL,
	bpcl_ref_compnr [varchar](10) NULL,
	bptc [varchar](3) NULL,
	bptc_ref_compnr [varchar](10) NULL,
	btsp [int] NULL,
	btsp_kw [varchar](255) NULL,
	btx1 [int] NULL,
	btx1_ref_compnr [varchar](10) NULL,
	btx2 [int] NULL,
	btx2_ref_compnr [varchar](10) NULL,
	cact [varchar](16) NULL,
	cadr [varchar](9) NULL,
	cadr_ref_compnr [varchar](10) NULL,
	casi [varchar](3) NULL,
	ccco [varchar](8) NULL,
	ccco_ref_compnr [varchar](10) NULL,
	ccof [varchar](6) NULL,
	ccty [varchar](3) NULL,
	ccty_cvat_ref_compnr [varchar](10) NULL,
	ccty_ref_compnr [varchar](10) NULL,
	cdec [varchar](3) NULL,
	cdec_ref_compnr [varchar](10) NULL,
	cdis_1 [varchar](3) NULL,
	cdis_10 [varchar](3) NULL,
	cdis_11 [varchar](3) NULL,
	cdis_2 [varchar](3) NULL,
	cdis_3 [varchar](3) NULL,
	cdis_4 [varchar](3) NULL,
	cdis_5 [varchar](3) NULL,
	cdis_6 [varchar](3) NULL,
	cdis_7 [varchar](3) NULL,
	cdis_8 [varchar](3) NULL,
	cdis_9 [varchar](3) NULL,
	ceno [varchar](24) NULL,
	cfap [int] NULL,
	cfap_kw [varchar](255) NULL,
	cfrw [varchar](3) NULL,
	citg [varchar](6) NULL,
	citt [varchar](3) NULL,
	citt_ref_compnr [varchar](10) NULL,
	ckor [int] NOT NULL,
	ckor_kw [varchar](255) NULL,
	clip [int] NULL,
	clip_kw [varchar](255) NULL,
	clot [varchar](20) NULL,
	clyn [int] NULL,
	clyn_kw [varchar](255) NULL,
	cmnf [varchar](6) NULL,
	cmnf_ref_compnr [varchar](10) NULL,
	cncd [varchar](6) NULL,
	cnig [int] NULL,
	cnig_kw [varchar](255) NULL,
	cnpt [int] NULL,
	cnpt_kw [varchar](255) NULL,
	comm [int] NULL,
	comm_kw [varchar](255) NULL,
	compnr [varchar](10) NOT NULL,
	cono [varchar](9) NULL,
	coop_1 [float] NULL,
	coop_2 [float] NULL,
	coop_3 [float] NULL,
	copr_1 [float] NULL,
	copr_2 [float] NULL,
	copr_3 [float] NULL,
	corg [int] NULL,
	corg_kw [varchar](255) NULL,
	cosn [varchar](8) NULL,
	cpay [varchar](3) NULL,
	cpay_ref_compnr [varchar](10) NULL,
	cpcl [varchar](6) NULL,
	cpcl_ref_compnr [varchar](10) NULL,
	cpcp [varchar](8) NULL,
	cpcp_ref_compnr [varchar](10) NULL,
	cpgp [varchar](6) NULL,
	cpgp_ref_compnr [varchar](10) NULL,
	cpln [varchar](6) NULL,
	cpln_ref_compnr [varchar](10) NULL,
	cprj [varchar](9) NULL,
	cprj_ref_compnr [varchar](10) NULL,
	cpva [int] NULL,
	crbn [int] NULL,
	crbn_kw [varchar](255) NULL,
	crcd [varchar](6) NULL,
	crcd_ref_compnr [varchar](10) NULL,
	crej [varchar](6) NULL,
	crej_ref_compnr [varchar](10) NULL,
	crit [varchar](255) NULL,
	crrf [int] NULL,
	crrf_kw [varchar](255) NULL,
	csgp [varchar](6) NULL,
	csgp_ref_compnr [varchar](10) NULL,
	cspa [varchar](16) NULL,
	csqn [int] NULL,
	cstl [varchar](4) NULL,
	ctcd [varchar](6) NULL,
	ctcd_ref_compnr [varchar](10) NULL,
	ctrj [varchar](5) NULL,
	cubp [varchar](3) NULL,
	cubp_ref_compnr [varchar](10) NULL,
	cucf [varchar](3) NULL,
	cumr [varchar](3) NULL,
	cupp [varchar](3) NULL,
	cupp_ref_compnr [varchar](10) NULL,
	cuqp [varchar](3) NULL,
	cuqp_ref_compnr [varchar](10) NULL,
	curq [varchar](3) NULL,
	curq_ref_compnr [varchar](10) NULL,
	cuva [float] NULL,
	cvat [varchar](9) NULL,
	cvbp [float] NULL,
	cvcf [float] NULL,
	cvmr [float] NULL,
	cvpp [float] NULL,
	cvqp [float] NULL,
	cvrq [float] NULL,
	cwar [varchar](6) NULL,
	cwar_ref_compnr [varchar](10) NULL,
	damt [float] NULL,
	ddon [int] NULL,
	ddta [datetime] NULL,
	ddtb [datetime] NULL,
	ddtc [datetime] NULL,
	ddtd [datetime] NULL,
	ddte [datetime] NULL,
	ddtf [datetime] NULL,
	deleted [varchar](10) NULL,
	dino [varchar](255) NULL,
	disc_1 [float] NULL,
	disc_10 [float] NULL,
	disc_11 [float] NULL,
	disc_2 [float] NULL,
	disc_3 [float] NULL,
	disc_4 [float] NULL,
	disc_5 [float] NULL,
	disc_6 [float] NULL,
	disc_7 [float] NULL,
	disc_8 [float] NULL,
	disc_9 [float] NULL,
	dmde_1 [varchar](9) NULL,
	dmde_10 [varchar](9) NULL,
	dmde_11 [varchar](9) NULL,
	dmde_2 [varchar](9) NULL,
	dmde_3 [varchar](9) NULL,
	dmde_4 [varchar](9) NULL,
	dmde_5 [varchar](9) NULL,
	dmde_6 [varchar](9) NULL,
	dmde_7 [varchar](9) NULL,
	dmde_8 [varchar](9) NULL,
	dmde_9 [varchar](9) NULL,
	dmse_1 [int] NULL,
	dmse_10 [int] NULL,
	dmse_11 [int] NULL,
	dmse_2 [int] NULL,
	dmse_3 [int] NULL,
	dmse_4 [int] NULL,
	dmse_5 [int] NULL,
	dmse_6 [int] NULL,
	dmse_7 [int] NULL,
	dmse_8 [int] NULL,
	dmse_9 [int] NULL,
	dmth_1 [int] NULL,
	dmth_10 [int] NULL,
	dmth_11 [int] NULL,
	dmth_2 [int] NULL,
	dmth_3 [int] NULL,
	dmth_4 [int] NULL,
	dmth_5 [int] NULL,
	dmth_6 [int] NULL,
	dmth_7 [int] NULL,
	dmth_8 [int] NULL,
	dmth_9 [int] NULL,
	dmth_kw_1 [varchar](255) NULL,
	dmth_kw_10 [varchar](255) NULL,
	dmth_kw_11 [varchar](255) NULL,
	dmth_kw_2 [varchar](255) NULL,
	dmth_kw_3 [varchar](255) NULL,
	dmth_kw_4 [varchar](255) NULL,
	dmth_kw_5 [varchar](255) NULL,
	dmth_kw_6 [varchar](255) NULL,
	dmth_kw_7 [varchar](255) NULL,
	dmth_kw_8 [varchar](255) NULL,
	dmth_kw_9 [varchar](255) NULL,
	dmty_1 [int] NULL,
	dmty_10 [int] NULL,
	dmty_11 [int] NULL,
	dmty_2 [int] NULL,
	dmty_3 [int] NULL,
	dmty_4 [int] NULL,
	dmty_5 [int] NULL,
	dmty_6 [int] NULL,
	dmty_7 [int] NULL,
	dmty_8 [int] NULL,
	dmty_9 [int] NULL,
	dmty_kw_1 [varchar](255) NULL,
	dmty_kw_10 [varchar](255) NULL,
	dmty_kw_11 [varchar](255) NULL,
	dmty_kw_2 [varchar](255) NULL,
	dmty_kw_3 [varchar](255) NULL,
	dmty_kw_4 [varchar](255) NULL,
	dmty_kw_5 [varchar](255) NULL,
	dmty_kw_6 [varchar](255) NULL,
	dmty_kw_7 [varchar](255) NULL,
	dmty_kw_8 [varchar](255) NULL,
	dmty_kw_9 [varchar](255) NULL,
	dorg_1 [int] NULL,
	dorg_10 [int] NULL,
	dorg_11 [int] NULL,
	dorg_2 [int] NULL,
	dorg_3 [int] NULL,
	dorg_4 [int] NULL,
	dorg_5 [int] NULL,
	dorg_6 [int] NULL,
	dorg_7 [int] NULL,
	dorg_8 [int] NULL,
	dorg_9 [int] NULL,
	dorg_kw_1 [varchar](255) NULL,
	dorg_kw_10 [varchar](255) NULL,
	dorg_kw_11 [varchar](255) NULL,
	dorg_kw_2 [varchar](255) NULL,
	dorg_kw_3 [varchar](255) NULL,
	dorg_kw_4 [varchar](255) NULL,
	dorg_kw_5 [varchar](255) NULL,
	dorg_kw_6 [varchar](255) NULL,
	dorg_kw_7 [varchar](255) NULL,
	dorg_kw_8 [varchar](255) NULL,
	dorg_kw_9 [varchar](255) NULL,
	dtrm [int] NULL,
	dtrm_kw [varchar](255) NULL,
	effn [int] NULL,
	elgb [int] NULL,
	elgb_kw [varchar](255) NULL,
	etpc [int] NULL,
	etpc_kw [varchar](255) NULL,
	exmt [int] NULL,
	exmt_kw [varchar](255) NULL,
	fire [int] NULL,
	fire_kw [varchar](255) NULL,
	fono [varchar](9) NULL,
	fopo [int] NULL,
	gefo [int] NULL,
	gefo_kw [varchar](255) NULL,
	glco [varchar](135) NULL,
	hisa [int] NULL,
	hisa_kw [varchar](255) NULL,
	iamt [float] NULL,
	invc [int] NULL,
	invc_kw [varchar](255) NULL,
	invd [datetime] NULL,
	invn [varchar](9) NULL,
	issp [int] NULL,
	issp_kw [varchar](255) NULL,
	item [varchar](47) NULL,
	item_ref_compnr [varchar](10) NULL,
	iwgt [float] NULL,
	iwun [varchar](3) NULL,
	iwun_ref_compnr [varchar](10) NULL,
	kitm [int] NULL,
	kitm_kw [varchar](255) NULL,
	lccl [varchar](12) NULL,
	lccl_ref_compnr [varchar](10) NULL,
	lcrq [int] NULL,
	lcrq_kw [varchar](255) NULL,
	ldam_1 [float] NULL,
	ldam_10 [float] NULL,
	ldam_11 [float] NULL,
	ldam_2 [float] NULL,
	ldam_3 [float] NULL,
	ldam_4 [float] NULL,
	ldam_5 [float] NULL,
	ldam_6 [float] NULL,
	ldam_7 [float] NULL,
	ldam_8 [float] NULL,
	ldam_9 [float] NULL,
	ldat [datetime] NULL,
	leng [float] NULL,
	logn [varchar](16) NULL,
	lsel [int] NULL,
	lsel_kw [varchar](255) NULL,
	lseq [int] NULL,
	lsid [varchar](255) NULL,
	lstn [varchar](6) NULL,
	manp [int] NULL,
	manp_kw [varchar](255) NULL,
	mitm [varchar](255) NULL,
	mnlp [int] NULL,
	mnsq [int] NULL,
	mnwo [varchar](9) NULL,
	mpnr [varchar](35) NULL,
	mpnr_cmnf_ref_compnr [varchar](10) NULL,
	mpsn [varchar](22) NULL,
	mpsn_ref_compnr [varchar](10) NULL,
	mrdt [datetime] NULL,
	oamt [float] NULL,
	odat [datetime] NULL,
	odno [varchar](9) NULL,
	odty [int] NULL,
	odty_kw [varchar](255) NULL,
	oltp [int] NULL,
	oltp_kw [varchar](255) NULL,
	oorn [varchar](9) NULL,
	opno [int] NULL,
	opon [int] NULL,
	orno [varchar](9) NOT NULL,
	osqn [int] NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	owno [varchar](255) NULL,
	ownr [varchar](9) NULL,
	ownr_ref_compnr [varchar](10) NULL,
	owns [int] NULL,
	owns_kw [varchar](255) NULL,
	paft [int] NULL,
	paft_kw [varchar](255) NULL,
	paya [varchar](3) NULL,
	pcsr [int] NULL,
	pcsr_kw [varchar](255) NULL,
	pdno [varchar](9) NULL,
	pegd [int] NULL,
	pegd_kw [varchar](255) NULL,
	pgmd [int] NULL,
	pgmd_kw [varchar](255) NULL,
	pmde [varchar](9) NULL,
	pmnd [int] NULL,
	pmnd_kw [varchar](255) NULL,
	pmni [int] NULL,
	pmni_kw [varchar](255) NULL,
	pmnt [int] NULL,
	pmnt_kw [varchar](255) NULL,
	pmse [int] NULL,
	pmsk [varchar](20) NULL,
	pono [int] NOT NULL,
	porg [int] NULL,
	porg_kw [varchar](255) NULL,
	posi [int] NULL,
	ppon [int] NULL,
	pric [float] NULL,
	prsg [varchar](3) NULL,
	prsg_ref_compnr [varchar](10) NULL,
	prtp [varchar](3) NULL,
	prtp_ref_compnr [varchar](10) NULL,
	pseq [int] NULL,
	ptpa [varchar](9) NULL,
	ptpa_ref_compnr [varchar](10) NULL,
	ptpe [varchar](6) NULL,
	ptpe_ref_compnr [varchar](10) NULL,
	qalt [int] NULL,
	qbbc [float] NULL,
	qccf [float] NULL,
	qiap [float] NULL,
	qibo [float] NULL,
	qibp [float] NULL,
	qidl [float] NULL,
	qiiv [float] NULL,
	qilh [float] NULL,
	qips [float] NULL,
	qirj [float] NULL,
	qish [float] NULL,
	qmmr [float] NULL,
	qono [varchar](9) NULL,
	qoor [float] NULL,
	qpon [int] NULL,
	qrrq [float] NULL,
	qseq [int] NULL,
	qual [int] NULL,
	qual_kw [varchar](255) NULL,
	rcod [varchar](6) NULL,
	rcod_ref_compnr [varchar](10) NULL,
	rdta [datetime] NULL,
	refs [varchar](255) NULL,
	rels [int] NULL,
	rels_kw [varchar](255) NULL,
	reno [varchar](16) NULL,
	reto [varchar](9) NULL,
	retp [int] NULL,
	rets [int] NULL,
	revi [varchar](6) NULL,
	revn [int] NULL,
	rqno [varchar](9) NULL,
	rqpo [int] NULL,
	rqtp [int] NULL,
	rqtp_kw [varchar](255) NULL,
	rseq [int] NULL,
	rtyn [int] NULL,
	rtyn_kw [varchar](255) NULL,
	rtyp [int] NULL,
	rtyp_kw [varchar](255) NULL,
	sbim [int] NULL,
	sbim_kw [varchar](255) NULL,
	sbmt [varchar](3) NULL,
	sbmt_ref_compnr [varchar](10) NULL,
	schu [int] NULL,
	schu_kw [varchar](255) NULL,
	sctp [int] NULL,
	sctp_kw [varchar](255) NULL,
	sdsc [int] NULL,
	sdsc_kw [varchar](255) NULL,
	sequencenumber [int] NULL,
	serl [varchar](30) NULL,
	sern [int] NOT NULL,
	serv [varchar](3) NULL,
	serv_ref_compnr [varchar](10) NULL,
	sfad [varchar](9) NULL,
	sfad_ref_compnr [varchar](10) NULL,
	sfbp [varchar](9) NULL,
	sfbp_ref_compnr [varchar](10) NULL,
	sfcn [varchar](9) NULL,
	sfsi [varchar](9) NULL,
	sfsi_ref_compnr [varchar](10) NULL,
	sfwh [varchar](6) NULL,
	shdt [datetime] NULL,
	site [varchar](9) NULL,
	site_ref_compnr [varchar](10) NULL,
	sorn [varchar](9) NULL,
	spcn [varchar](22) NULL,
	spon [int] NULL,
	sqnb [int] NOT NULL,
	srpo [int] NULL,
	srsq [int] NULL,
	srvo [varchar](9) NULL,
	sseq [int] NULL,
	stat [int] NULL,
	stat_kw [varchar](255) NULL,
	stcd [int] NULL,
	stcd_kw [varchar](255) NULL,
	stdc [float] NULL,
	stsc [int] NULL,
	stsc_kw [varchar](255) NULL,
	stsd [int] NULL,
	stsd_kw [varchar](255) NULL,
	styp [int] NULL,
	styp_kw [varchar](255) NULL,
	subc [int] NULL,
	subc_kw [varchar](255) NULL,
	tapr [float] NULL,
	taxp [int] NULL,
	taxp_kw [varchar](255) NULL,
	thic [float] NULL,
	ztimestamp [datetime] NULL,
	tpbk [varchar](9) NULL,
	tpbk_ref_compnr [varchar](10) NULL,
	tpbk_tpbl_ref_compnr [varchar](10) NULL,
	tpbl [int] NULL,
	trdt [datetime] NOT NULL,
	txta [int] NULL,
	txta_ref_compnr [varchar](10) NULL,
	username [varchar](8) NULL,
	vrpr [int] NULL,
	vrpr_kw [varchar](255) NULL,
	widt [float] NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (pono)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur450]
Description: This is a DST table for Accounts Payable Purchase Order History

Data Type: Dimension Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur450];

CREATE TABLE [acq101].[dst_tdpur450] 
(
	adin [varchar](22) NULL,
	aitc [varchar](255) NULL,
	akcd [varchar](2) NULL,
	akcd_ref_compnr [varchar](10) NULL,
	bgrb [int] NULL,
	bgrb_kw [varchar](255) NULL,
	bgrq [int] NULL,
	bgrq_kw [varchar](255) NULL,
	bpcl [varchar](12) NULL,
	bpcl_ref_compnr [varchar](10) NULL,
	bppr [varchar](9) NULL,
	bppr_ref_compnr [varchar](10) NULL,
	bptx [varchar](9) NULL,
	bptx_ref_compnr [varchar](10) NULL,
	cadr [varchar](9) NULL,
	cadr_ref_compnr [varchar](10) NULL,
	casi [varchar](3) NULL,
	cbrn [varchar](6) NULL,
	cbrn_ref_compnr [varchar](10) NULL,
	ccon [varchar](9) NULL,
	ccon_ref_compnr [varchar](10) NULL,
	ccrs [varchar](3) NULL,
	ccrs_ref_compnr [varchar](10) NULL,
	ccty [varchar](3) NULL,
	ccur [varchar](3) NULL,
	ccur_ref_compnr [varchar](10) NULL,
	cdec [varchar](3) NULL,
	cdec_ref_compnr [varchar](10) NULL,
	cfrw [varchar](3) NULL,
	cfrw_ref_compnr [varchar](10) NULL,
	chrq [int] NULL,
	chrq_kw [varchar](255) NULL,
	citt [varchar](3) NULL,
	citt_ref_compnr [varchar](10) NULL,
	cofc [varchar](6) NULL,
	cofc_ref_compnr [varchar](10) NULL,
	comm [int] NULL,
	comm_kw [varchar](255) NULL,
	compnr [varchar](10) NOT NULL,
	cons [int] NULL,
	cons_kw [varchar](255) NULL,
	corg [int] NULL,
	corg_kw [varchar](255) NULL,
	cosn [varchar](8) NULL,
	cotp [varchar](3) NULL,
	cotp_ref_compnr [varchar](10) NULL,
	cpay [varchar](3) NULL,
	cpay_ref_compnr [varchar](10) NULL,
	cplp [varchar](3) NULL,
	cplp_ref_compnr [varchar](10) NULL,
	crby [varchar](16) NULL,
	crcd [varchar](6) NULL,
	crcd_ref_compnr [varchar](10) NULL,
	crcl [int] NULL,
	crcl_kw [varchar](255) NULL,
	crdt [datetime] NULL,
	creg [varchar](3) NULL,
	creg_ref_compnr [varchar](10) NULL,
	crht [int] NULL,
	crht_ref_compnr [varchar](10) NULL,
	crin [int] NULL,
	crin_kw [varchar](255) NULL,
	cror [int] NULL,
	cror_kw [varchar](255) NULL,
	crrq [int] NULL,
	crrq_kw [varchar](255) NULL,
	ctcd [varchar](6) NULL,
	ctcd_ref_compnr [varchar](10) NULL,
	ctrj [varchar](5) NULL,
	cvyn [int] NULL,
	cvyn_kw [varchar](255) NULL,
	cwar [varchar](6) NULL,
	cwar_ref_compnr [varchar](10) NULL,
	ddat [datetime] NULL,
	ddtc [datetime] NULL,
	deleted [varchar](10) NULL,
	drct [int] NULL,
	drct_kw [varchar](255) NULL,
	egen [int] NULL,
	egen_kw [varchar](255) NULL,
	etpc [int] NULL,
	etpc_kw [varchar](255) NULL,
	fdpt [varchar](6) NULL,
	fdpt_ref_compnr [varchar](10) NULL,
	gdat [datetime] NULL,
	hdst [int] NULL,
	hdst_kw [varchar](255) NULL,
	hisa [int] NULL,
	hisa_kw [varchar](255) NULL,
	hsta [int] NULL,
	hsta_kw [varchar](255) NULL,
	iafc [int] NULL,
	iafc_kw [varchar](255) NULL,
	iebp [int] NULL,
	iebp_kw [varchar](255) NULL,
	ifad [varchar](9) NULL,
	ifad_ref_compnr [varchar](10) NULL,
	ifbp [varchar](9) NULL,
	ifbp_ref_compnr [varchar](10) NULL,
	ifcn [varchar](9) NULL,
	item [varchar](47) NULL,
	item_ref_compnr [varchar](10) NULL,
	lccl [varchar](12) NULL,
	lccl_ref_compnr [varchar](10) NULL,
	lcrq [int] NULL,
	lcrq_kw [varchar](255) NULL,
	logn [varchar](16) NULL,
	mcfr [int] NULL,
	mcfr_kw [varchar](255) NULL,
	nauc [int] NULL,
	nauc_kw [varchar](255) NULL,
	oamt [float] NULL,
	odat [datetime] NULL,
	odis [float] NULL,
	odno [varchar](9) NULL,
	odty [int] NULL,
	odty_kw [varchar](255) NULL,
	opor [varchar](9) NULL,
	orno [varchar](9) NOT NULL,
	otad [varchar](9) NULL,
	otad_ref_compnr [varchar](10) NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	otcn [varchar](9) NULL,
	paft [int] NULL,
	paft_kw [varchar](255) NULL,
	pagr [int] NULL,
	pagr_kw [varchar](255) NULL,
	pcod [varchar](3) NULL,
	zplan [varchar](9) NULL,
	plan_ref_compnr [varchar](10) NULL,
	pmnd [int] NULL,
	pmnd_kw [varchar](255) NULL,
	pmni [int] NULL,
	pmni_kw [varchar](255) NULL,
	pmnt [int] NULL,
	pmnt_kw [varchar](255) NULL,
	prno [varchar](9) NULL,
	prno_ref_compnr [varchar](10) NULL,
	ptad [varchar](9) NULL,
	ptad_ref_compnr [varchar](10) NULL,
	ptbp [varchar](9) NULL,
	ptbp_ref_compnr [varchar](10) NULL,
	ptcn [varchar](9) NULL,
	ptmr [varchar](6) NULL,
	ptpa [varchar](9) NULL,
	ptpa_ref_compnr [varchar](10) NULL,
	ptss [varchar](6) NULL,
	ragr [varchar](16) NULL,
	ratd [datetime] NULL,
	ratf_1 [int] NULL,
	ratf_2 [int] NULL,
	ratf_3 [int] NULL,
	ratp_1 [float] NULL,
	ratp_2 [float] NULL,
	ratp_3 [float] NULL,
	ratt [varchar](3) NULL,
	ratt_ref_compnr [varchar](10) NULL,
	raur [int] NULL,
	raur_kw [varchar](255) NULL,
	refa [varchar](255) NULL,
	refb [varchar](255) NULL,
	retr [varchar](6) NULL,
	retr_ref_compnr [varchar](10) NULL,
	revi [varchar](6) NULL,
	revn [int] NULL,
	sbim [int] NULL,
	sbim_kw [varchar](255) NULL,
	sbmt [varchar](3) NULL,
	sbmt_ref_compnr [varchar](10) NULL,
	schu [int] NULL,
	schu_kw [varchar](255) NULL,
	segs [varchar](3) NULL,
	segs_ref_compnr [varchar](10) NULL,
	sequencenumber [int] NULL,
	sfad [varchar](9) NULL,
	sfad_ref_compnr [varchar](10) NULL,
	sfbp [varchar](9) NULL,
	sfbp_ref_compnr [varchar](10) NULL,
	sfcn [varchar](9) NULL,
	site [varchar](9) NULL,
	site_ref_compnr [varchar](10) NULL,
	sorn [varchar](255) NULL,
	ssip [varchar](3) NULL,
	ssmr [varchar](3) NULL,
	ssmr_ref_compnr [varchar](10) NULL,
	stad [varchar](9) NULL,
	stad_ref_compnr [varchar](10) NULL,
	stat [int] NULL,
	stat_kw [varchar](255) NULL,
	styp [int] NULL,
	styp_kw [varchar](255) NULL,
	term [int] NULL,
	term_kw [varchar](255) NULL,
	ztimestamp [datetime] NULL,
	tqal [int] NULL,
	tqal_kw [varchar](255) NULL,
	trdt [datetime] NOT NULL,
	txta [int] NULL,
	txta_ref_compnr [varchar](10) NULL,
	txtb [int] NULL,
	txtb_ref_compnr [varchar](10) NULL,
	username [varchar](8) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (orno)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur430]
Description: This is a DST table for Accounts Payable Purchase Payable Receipts for Orders and Schedules 

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur430];

CREATE TABLE [acq101].[dst_tdpur430] 
(
	amld [float] NULL,
	amod [float] NULL,
	ccof [varchar](6) NULL,
	cdis_1 [varchar](3) NULL,
	cdis_10 [varchar](3) NULL,
	cdis_11 [varchar](3) NULL,
	cdis_2 [varchar](3) NULL,
	cdis_3 [varchar](3) NULL,
	cdis_4 [varchar](3) NULL,
	cdis_5 [varchar](3) NULL,
	cdis_6 [varchar](3) NULL,
	cdis_7 [varchar](3) NULL,
	cdis_8 [varchar](3) NULL,
	cdis_9 [varchar](3) NULL,
	cnig [int] NULL,
	cnig_kw [varchar](255) NULL,
	compnr [varchar](10) NOT NULL,
	cono [varchar](9) NULL,
	cpon [int] NULL,
	csqn [int] NULL,
	cupp [varchar](3) NULL,
	cupp_ref_compnr [varchar](10) NULL,
	cvpp [float] NULL,
	deleted [varchar](10) NULL,
	disc_1 [float] NULL,
	disc_10 [float] NULL,
	disc_11 [float] NULL,
	disc_2 [float] NULL,
	disc_3 [float] NULL,
	disc_4 [float] NULL,
	disc_5 [float] NULL,
	disc_6 [float] NULL,
	disc_7 [float] NULL,
	disc_8 [float] NULL,
	disc_9 [float] NULL,
	dmde_1 [varchar](9) NULL,
	dmde_10 [varchar](9) NULL,
	dmde_11 [varchar](9) NULL,
	dmde_2 [varchar](9) NULL,
	dmde_3 [varchar](9) NULL,
	dmde_4 [varchar](9) NULL,
	dmde_5 [varchar](9) NULL,
	dmde_6 [varchar](9) NULL,
	dmde_7 [varchar](9) NULL,
	dmde_8 [varchar](9) NULL,
	dmde_9 [varchar](9) NULL,
	dmse_1 [int] NULL,
	dmse_10 [int] NULL,
	dmse_11 [int] NULL,
	dmse_2 [int] NULL,
	dmse_3 [int] NULL,
	dmse_4 [int] NULL,
	dmse_5 [int] NULL,
	dmse_6 [int] NULL,
	dmse_7 [int] NULL,
	dmse_8 [int] NULL,
	dmse_9 [int] NULL,
	dmth_1 [int] NULL,
	dmth_10 [int] NULL,
	dmth_11 [int] NULL,
	dmth_2 [int] NULL,
	dmth_3 [int] NULL,
	dmth_4 [int] NULL,
	dmth_5 [int] NULL,
	dmth_6 [int] NULL,
	dmth_7 [int] NULL,
	dmth_8 [int] NULL,
	dmth_9 [int] NULL,
	dmth_kw_1 [varchar](255) NULL,
	dmth_kw_10 [varchar](255) NULL,
	dmth_kw_11 [varchar](255) NULL,
	dmth_kw_2 [varchar](255) NULL,
	dmth_kw_3 [varchar](255) NULL,
	dmth_kw_4 [varchar](255) NULL,
	dmth_kw_5 [varchar](255) NULL,
	dmth_kw_6 [varchar](255) NULL,
	dmth_kw_7 [varchar](255) NULL,
	dmth_kw_8 [varchar](255) NULL,
	dmth_kw_9 [varchar](255) NULL,
	dmty_1 [int] NULL,
	dmty_10 [int] NULL,
	dmty_11 [int] NULL,
	dmty_2 [int] NULL,
	dmty_3 [int] NULL,
	dmty_4 [int] NULL,
	dmty_5 [int] NULL,
	dmty_6 [int] NULL,
	dmty_7 [int] NULL,
	dmty_8 [int] NULL,
	dmty_9 [int] NULL,
	dmty_kw_1 [varchar](255) NULL,
	dmty_kw_10 [varchar](255) NULL,
	dmty_kw_11 [varchar](255) NULL,
	dmty_kw_2 [varchar](255) NULL,
	dmty_kw_3 [varchar](255) NULL,
	dmty_kw_4 [varchar](255) NULL,
	dmty_kw_5 [varchar](255) NULL,
	dmty_kw_6 [varchar](255) NULL,
	dmty_kw_7 [varchar](255) NULL,
	dmty_kw_8 [varchar](255) NULL,
	dmty_kw_9 [varchar](255) NULL,
	dorg_1 [int] NULL,
	dorg_10 [int] NULL,
	dorg_11 [int] NULL,
	dorg_2 [int] NULL,
	dorg_3 [int] NULL,
	dorg_4 [int] NULL,
	dorg_5 [int] NULL,
	dorg_6 [int] NULL,
	dorg_7 [int] NULL,
	dorg_8 [int] NULL,
	dorg_9 [int] NULL,
	dorg_kw_1 [varchar](255) NULL,
	dorg_kw_10 [varchar](255) NULL,
	dorg_kw_11 [varchar](255) NULL,
	dorg_kw_2 [varchar](255) NULL,
	dorg_kw_3 [varchar](255) NULL,
	dorg_kw_4 [varchar](255) NULL,
	dorg_kw_5 [varchar](255) NULL,
	dorg_kw_6 [varchar](255) NULL,
	dorg_kw_7 [varchar](255) NULL,
	dorg_kw_8 [varchar](255) NULL,
	dorg_kw_9 [varchar](255) NULL,
	dtrm [int] NULL,
	dtrm_kw [varchar](255) NULL,
	elgb [int] NULL,
	elgb_kw [varchar](255) NULL,
	ftdt [datetime] NULL,
	iamt [float] NULL,
	invd [datetime] NULL,
	invn [varchar](9) NULL,
	ldam_1 [float] NULL,
	ldam_10 [float] NULL,
	ldam_11 [float] NULL,
	ldam_2 [float] NULL,
	ldam_3 [float] NULL,
	ldam_4 [float] NULL,
	ldam_5 [float] NULL,
	ldam_6 [float] NULL,
	ldam_7 [float] NULL,
	ldam_8 [float] NULL,
	ldam_9 [float] NULL,
	opsq [int] NULL,
	orno [varchar](9) NOT NULL,
	pamt [float] NULL,
	pmde [varchar](9) NULL,
	pmse [int] NULL,
	pono [int] NOT NULL,
	porg [int] NULL,
	porg_kw [varchar](255) NULL,
	pric [float] NULL,
	zproc [int] NULL,
	proc_kw [varchar](255) NULL,
	prsg [varchar](3) NULL,
	prsg_ref_compnr [varchar](10) NULL,
	psqn [int] NOT NULL,
	ptyp [int] NULL,
	ptyp_kw [varchar](255) NULL,
	qiiv [float] NULL,
	qipr [float] NULL,
	ract [int] NULL,
	ract_kw [varchar](255) NULL,
	rarc [int] NULL,
	rarc_kw [varchar](255) NULL,
	rsqn [int] NOT NULL,
	sequencenumber [int] NULL,
	sqnb [int] NOT NULL,
	stsc [int] NULL,
	stsc_kw [varchar](255) NULL,
	stsd [int] NULL,
	stsd_kw [varchar](255) NULL,
	styp [int] NULL,
	styp_kw [varchar](255) NULL,
	ztimestamp [datetime] NULL,
	uldt [datetime] NULL,
	usdt [datetime] NULL,
	username [varchar](8) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (psqn)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tfacp200]
Description: This is a DST table for Accounts Payable Open Items (Purchase Invoices and Payments)

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tfacp200];

CREATE TABLE [acq101].[dst_tfacp200] 
(
	adcd [varchar](3) NULL,
	adty [int] NULL,
	adty_kw [varchar](255) NULL,
	afpy [int] NULL,
	afpy_kw [varchar](255) NULL,
	amnt [float] NULL,
	amth_1 [float] NULL,
	amth_2 [float] NULL,
	amth_3 [float] NULL,
	amti [float] NULL,
	appr [int] NULL,
	appr_kw [varchar](255) NULL,
	autm [int] NULL,
	autm_kw [varchar](255) NULL,
	baca_1 [float] NULL,
	baca_2 [float] NULL,
	baca_3 [float] NULL,
	baco [float] NULL,
	bahc_1 [float] NULL,
	bahc_2 [float] NULL,
	bahc_3 [float] NULL,
	bala [float] NULL,
	balc [float] NULL,
	balh_1 [float] NULL,
	balh_2 [float] NULL,
	balh_3 [float] NULL,
	bank [varchar](3) NULL,
	basi [float] NULL,
	bdat [varchar](10) NULL,
	bdsp [int] NULL,
	bdsp_kw [varchar](255) NULL,
	bkrn [varchar](27) NULL,
	blac [int] NULL,
	blac_kw [varchar](255) NULL,
	bloc [varchar](3) NULL,
	bloc_ref_compnr [varchar](10) NULL,
	bref [varchar](3) NULL,
	bref_ref_compnr [varchar](10) NULL,
	btno [int] NULL,
	bust [int] NULL,
	bust_kw [varchar](255) NULL,
	ccrs [varchar](3) NULL,
	ccrs_ref_compnr [varchar](10) NULL,
	ccur [varchar](3) NULL,
	ccur_ref_compnr [varchar](10) NULL,
	cdam_1 [float] NULL,
	cdam_2 [float] NULL,
	cdam_3 [float] NULL,
	cfrs [varchar](6) NULL,
	cfrs_ref_compnr [varchar](10) NULL,
	clus [varchar](9) NULL,
	compnr [varchar](10) NOT NULL,
	cpay [varchar](3) NULL,
	cpay_ref_compnr [varchar](10) NULL,
	cvat [varchar](9) NULL,
	cvat_ref_compnr [varchar](10) NULL,
	dapr [int] NULL,
	dc1a [float] NULL,
	dc1h_1 [float] NULL,
	dc1h_2 [float] NULL,
	dc1h_3 [float] NULL,
	dc1i [float] NULL,
	dc2a [float] NULL,
	dc2h_1 [float] NULL,
	dc2h_2 [float] NULL,
	dc2h_3 [float] NULL,
	dc2i [float] NULL,
	dc3a [float] NULL,
	dc3h_1 [float] NULL,
	dc3h_2 [float] NULL,
	dc3h_3 [float] NULL,
	dc3i [float] NULL,
	deleted [varchar](10) NULL,
	did1 [varchar](10) NULL,
	did2 [varchar](10) NULL,
	did3 [varchar](10) NULL,
	dim1 [varchar](9) NULL,
	dim2 [varchar](9) NULL,
	dim3 [varchar](9) NULL,
	dim4 [varchar](9) NULL,
	dim5 [varchar](9) NULL,
	dim6 [varchar](9) NULL,
	dim7 [varchar](9) NULL,
	dim8 [varchar](9) NULL,
	dim9 [varchar](9) NULL,
	dm10 [varchar](9) NULL,
	dm11 [varchar](9) NULL,
	dm12 [varchar](9) NULL,
	doca [int] NULL,
	docd [varchar](10) NULL,
	docn [int] NOT NULL,
	dued [varchar](10) NULL,
	edtp [int] NULL,
	edtp_kw [varchar](255) NULL,
	enia [int] NULL,
	enia_kw [varchar](255) NULL,
	iadr [varchar](9) NULL,
	iadr_ref_compnr [varchar](10) NULL,
	ifbp [varchar](9) NULL,
	ifbp_ref_compnr [varchar](10) NULL,
	ildp [int] NULL,
	ildp_kw [varchar](255) NULL,
	irdt [varchar](10) NULL,
	isup [varchar](255) NULL,
	lapa [float] NULL,
	laph_1 [float] NULL,
	laph_2 [float] NULL,
	laph_3 [float] NULL,
	lapi [float] NULL,
	leac [varchar](12) NULL,
	leac_ref_compnr [varchar](10) NULL,
	line [int] NOT NULL,
	link [float] NULL,
	lino [int] NOT NULL,
	liqd [varchar](10) NULL,
	zload [varchar](9) NULL,
	loco [int] NULL,
	lpdt [varchar](10) NULL,
	lvat [int] NULL,
	lvat_kw [varchar](255) NULL,
	ninv [int] NOT NULL,
	oinv [int] NULL,
	optb [varchar](9) NULL,
	optb_ref_compnr [varchar](10) NULL,
	orno [varchar](9) NULL,
	osch [int] NULL,
	osup [varchar](255) NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	otyp [varchar](3) NULL,
	otyp_ref_compnr [varchar](10) NULL,
	pada [float] NULL,
	padh_1 [float] NULL,
	padh_2 [float] NULL,
	padh_3 [float] NULL,
	padi [float] NULL,
	papr [int] NULL,
	papr_kw [varchar](255) NULL,
	paya [varchar](3) NULL,
	paya_ref_compnr [varchar](10) NULL,
	payd [int] NULL,
	payl [int] NULL,
	paym [varchar](3) NULL,
	paym_ref_compnr [varchar](10) NULL,
	payt [varchar](3) NULL,
	pcom [int] NULL,
	pdat [varchar](10) NULL,
	pdif [float] NULL,
	pdoc [varchar](15) NULL,
	pfre [int] NULL,
	pfre_kw [varchar](255) NULL,
	post [int] NULL,
	prin [int] NULL,
	prin_kw [varchar](255) NULL,
	prod [int] NULL,
	ptbp [varchar](9) NULL,
	ptbp_bank_ref_compnr [varchar](10) NULL,
	ptbp_ref_compnr [varchar](10) NULL,
	ptyp [varchar](6) NULL,
	ptyp_ref_compnr [varchar](10) NULL,
	pysh [int] NULL,
	pysh_kw [varchar](255) NULL,
	rade [int] NULL,
	rade_kw [varchar](255) NULL,
	ragr [varchar](16) NULL,
	ratd [datetime] NULL,
	rate_1 [float] NULL,
	rate_2 [float] NULL,
	rate_3 [float] NULL,
	ratf_1 [int] NULL,
	ratf_2 [int] NULL,
	ratf_3 [int] NULL,
	rcpt [int] NULL,
	rcpt_kw [varchar](255) NULL,
	reas [varchar](3) NULL,
	reas_ref_compnr [varchar](10) NULL,
	refr [varchar](255) NULL,
	rtyp [varchar](3) NULL,
	schn [int] NULL,
	sequencenumber [int] NULL,
	sgtp [int] NULL,
	sgtp_kw [varchar](255) NULL,
	shpi [varchar](9) NULL,
	shpm [varchar](255) NULL,
	stap [int] NULL,
	stap_kw [varchar](255) NULL,
	stat [int] NULL,
	stat_kw [varchar](255) NULL,
	step [int] NULL,
	step_kw [varchar](255) NULL,
	subc [int] NULL,
	subc_kw [varchar](255) NULL,
	svah_1 [float] NULL,
	svah_2 [float] NULL,
	svah_3 [float] NULL,
	svam [float] NULL,
	tapr [varchar](3) NULL,
	tbrl [float] NULL,
	tdoc [varchar](3) NOT NULL,
	tdoc_ref_compnr [varchar](10) NULL,
	text [int] NULL,
	text_ref_compnr [varchar](10) NULL,
	ztimestamp [datetime] NULL,
	tnpn [varchar](9) NULL,
	tore_1 [float] NULL,
	tore_2 [float] NULL,
	tore_3 [float] NULL,
	tpay [int] NULL,
	tpay_kw [varchar](255) NULL,
	ttyp [varchar](3) NOT NULL,
	ttyp_ref_compnr [varchar](10) NULL,
	txdt [varchar](10) NULL,
	txtb [int] NULL,
	txtb_ref_compnr [varchar](10) NULL,
	typa [varchar](3) NULL,
	typa_ref_compnr [varchar](10) NULL,
	zuser [varchar](16) NULL,
	username [varchar](8) NULL,
	vata [float] NULL,
	vatc [varchar](3) NULL,
	vatc_cvat_ref_compnr [varchar](10) NULL,
	vatc_ref_compnr [varchar](10) NULL,
	vath_1 [float] NULL,
	vath_2 [float] NULL,
	vath_3 [float] NULL,
	vati [float] NULL,
	vatp [int] NULL,
	vaty [int] NULL,
	vrsm [varchar](10) NULL,
	whti [int] NULL,
	whti_kw [varchar](255) NULL,
	wtph_1 [float] NULL,
	wtph_2 [float] NULL,
	wtph_3 [float] NULL,
	wtpi [float] NULL,
	zyear [int] NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (lino)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur406]
Description: This is a DST table for Accounts Payable Purchase Actual receipts

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur406];

CREATE TABLE [acq101].[dst_tdpur406] 
(
	afrw [varchar](3) NULL,
	afrw_ref_compnr [varchar](10) NULL,
	amld [float] NULL,
	amod [float] NULL,
	arej [int] NULL,
	arej_kw [varchar](255) NULL,
	asnl [varchar](255) NULL,
	asno [varchar](255) NULL,
	bgxc [int] NULL,
	bgxc_kw [varchar](255) NULL,
	cmnf [varchar](6) NULL,
	cmnf_ref_compnr [varchar](10) NULL,
	compnr [varchar](10) NOT NULL,
	conf [int] NULL,
	conf_kw [varchar](255) NULL,
	coop_1 [float] NULL,
	coop_2 [float] NULL,
	coop_3 [float] NULL,
	copr_1 [float] NULL,
	copr_2 [float] NULL,
	copr_3 [float] NULL,
	crej [varchar](6) NULL,
	crej_ref_compnr [varchar](10) NULL,
	damt [float] NULL,
	ddte [datetime] NULL,
	deleted [varchar](10) NULL,
	deln [varchar](19) NULL,
	dino [varchar](255) NULL,
	fire [int] NULL,
	fire_kw [varchar](255) NULL,
	ldat [datetime] NULL,
	zload [varchar](9) NULL,
	lssn [varchar](22) NULL,
	lssn_ref_compnr [varchar](10) NULL,
	mpnr [varchar](35) NULL,
	mpnr_cmnf_ref_compnr [varchar](10) NULL,
	onpr [float] NULL,
	orno [varchar](9) NOT NULL,
	orno_ref_compnr [varchar](10) NULL,
	pono [int] NOT NULL,
	qiap [float] NULL,
	qidl [float] NULL,
	qips [float] NULL,
	qirj [float] NULL,
	qual [int] NULL,
	qual_kw [varchar](255) NULL,
	rcld [datetime] NULL,
	rcno [varchar](9) NULL,
	refa [varchar](255) NULL,
	revi [varchar](6) NULL,
	rseq [int] NULL,
	rsqn [int] NOT NULL,
	sequencenumber [int] NULL,
	shdt [datetime] NULL,
	shpm [varchar](9) NULL,
	sqnb [int] NOT NULL,
	ztimestamp [datetime] NULL,
	username [varchar](8) NULL,
	wght [float] NULL,
	wtun [varchar](3) NULL,
	wtun_ref_compnr [int] NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (rsqn)
)
GO


/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur403]
Description: This is a DST table for Accounts Payable Purchase Order Bill of Material

Data Type: Dimension Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur403];

CREATE TABLE [acq101].[dst_tdpur403] 
(
	compnr [varchar](10) NOT NULL,
	deleted [varchar](10) NULL,
	orno [varchar](9) NOT NULL,
	orno_pono_sqnb_ref_compnr [varchar](10) NULL,
	orno_ref_compnr [varchar](10) NULL,
	ponb [int] NOT NULL,
	pono [int] NOT NULL,
	qibm [float] NULL,
	sequencenumber [int] NULL,
	sitm [varchar](47) NULL,
	sitm_ref_compnr [varchar](10) NULL,
	sqnb [int] NOT NULL,
	ztimestamp [datetime] NULL,
	username [varchar](8) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (pono)
)
GO


/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur094]
Description: This is a DST table for Accounts Payable Purchase Order Types

Data Type: Dimension Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur094];

CREATE TABLE [acq101].[dst_tdpur094] 
(
	cbor [int] NULL,
	cbor_kw [varchar](255) NULL,
	cfnm [int] NULL,
	cfnm_kw [varchar](255) NULL,
	cnsp [int] NULL,
	cnsp_kw [varchar](255) NULL,
	cnsr [int] NULL,
	cnsr_kw [varchar](255) NULL,
	compnr [varchar](10) NOT NULL,
	coun [int] NULL,
	coun_kw [varchar](255) NULL,
	deleted [varchar](10) NULL,
	drct [int] NULL,
	drct_kw [varchar](255) NULL,
	dsca [varchar](255) NULL,
	efdt [datetime] NULL,
	etpc [int] NULL,
	etpc_kw [varchar](255) NULL,
	exdt [datetime] NULL,
	ngpc [varchar](3) NULL,
	ngpc_ref_compnr [varchar](10) NULL,
	ngpc_sepc_ref_compnr [varchar](10) NULL,
	ngpo [varchar](3) NULL,
	ngpo_ref_compnr [varchar](10) NULL,
	ngpo_sepo_ref_compnr [varchar](10) NULL,
	ngpq [varchar](3) NULL,
	ngpq_ref_compnr [varchar](10) NULL,
	ngpq_sepq_ref_compnr [varchar](10) NULL,
	pmsk [varchar](20) NULL,
	potp [varchar](3) NOT NULL,
	zproc [varchar](6) NULL,
	reto [int] NULL,
	reto_kw [varchar](255) NULL,
	sepc [varchar](8) NULL,
	sepo [varchar](8) NULL,
	sepq [varchar](8) NULL,
	sequencenumber [int] NULL,
	slcp [int] NULL,
	slcp_kw [varchar](255) NULL,
	subc [int] NULL,
	subc_kw [varchar](255) NULL,
	sund [int] NULL,
	sund_kw [varchar](255) NULL,
	ztimestamp [datetime] NULL,
	username [varchar](8) NULL,
	wrhp [varchar](3) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (potp)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur300]
Description: This is a DST table for Accounts Payable Purchase Contracts

Data Type: Dimension Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur300];

CREATE TABLE [acq101].[dst_tdpur300] 
(
	bpcl [varchar](12) NULL,
	bpcl_ref_compnr [varchar](10) NULL,
	cadr [varchar](9) NULL,
	cadr_ref_compnr [varchar](10) NULL,
	ccon [varchar](9) NULL,
	ccon_ref_compnr [varchar](10) NULL,
	ccrs [varchar](3) NULL,
	ccrs_ref_compnr [varchar](10) NULL,
	ccty [varchar](3) NULL,
	ccur [varchar](3) NULL,
	ccur_ref_compnr [varchar](10) NULL,
	cdat [datetime] NULL,
	cdec [varchar](3) NULL,
	cdec_ref_compnr [varchar](10) NULL,
	cdes [varchar](255) NULL,
	cfrw [varchar](3) NULL,
	cfrw_ref_compnr [varchar](10) NULL,
	chrq [int] NULL,
	chrq_kw [varchar](255) NULL,
	cofc [varchar](6) NULL,
	cofc_ref_compnr [varchar](10) NULL,
	compnr [varchar](10) NOT NULL,
	conf [varchar](255) NULL,
	cono [varchar](9) NOT NULL,
	copc [int] NULL,
	copc_kw [varchar](255) NULL,
	cotp [varchar](3) NULL,
	cotp_ref_compnr [varchar](10) NULL,
	cpay [varchar](3) NULL,
	cpay_ref_compnr [varchar](10) NULL,
	crby [varchar](16) NULL,
	crdt [datetime] NULL,
	crht [int] NULL,
	crht_ref_compnr [varchar](10) NULL,
	crin [int] NULL,
	crin_kw [varchar](255) NULL,
	crrq [int] NULL,
	crrq_kw [varchar](255) NULL,
	crst [int] NULL,
	crst_kw [varchar](255) NULL,
	csts [int] NULL,
	csts_kw [varchar](255) NULL,
	cvyn [int] NULL,
	cvyn_kw [varchar](255) NULL,
	cwar [varchar](6) NULL,
	cwar_ref_compnr [varchar](10) NULL,
	deleted [varchar](10) NULL,
	edat [datetime] NULL,
	icap [int] NULL,
	icap_kw [varchar](255) NULL,
	icpr [int] NULL,
	icpr_kw [varchar](255) NULL,
	icyp [int] NULL,
	icyp_kw [varchar](255) NULL,
	ifad [varchar](9) NULL,
	ifad_ref_compnr [varchar](10) NULL,
	ifbp [varchar](9) NULL,
	ifbp_ref_compnr [varchar](10) NULL,
	ifcn [varchar](9) NULL,
	ifcn_ref_compnr [varchar](10) NULL,
	lcmp [int] NULL,
	lcmp_ref_compnr [varchar](10) NULL,
	nope [int] NULL,
	ocon [varchar](9) NULL,
	ocon_ref_compnr [varchar](10) NULL,
	otad [varchar](9) NULL,
	otad_ref_compnr [varchar](10) NULL,
	otbp [varchar](9) NULL,
	otbp_ref_compnr [varchar](10) NULL,
	otcn [varchar](9) NULL,
	otcn_ref_compnr [varchar](10) NULL,
	ptad [varchar](9) NULL,
	ptad_ref_compnr [varchar](10) NULL,
	ptbp [varchar](9) NULL,
	ptbp_ref_compnr [varchar](10) NULL,
	ptcn [varchar](9) NULL,
	ptcn_ref_compnr [varchar](10) NULL,
	ptpa [varchar](9) NULL,
	ptpa_ref_compnr [varchar](10) NULL,
	rcmp [int] NULL,
	rcmp_ref_compnr [varchar](10) NULL,
	rcsi [varchar](9) NULL,
	rcsi_ref_compnr [varchar](10) NULL,
	refb [varchar](255) NULL,
	refe [varchar](255) NULL,
	revn [int] NULL,
	rofc [varchar](6) NULL,
	rofc_ref_compnr [varchar](10) NULL,
	sdat [datetime] NULL,
	sequencenumber [int] NULL,
	sfad [varchar](9) NULL,
	sfad_ref_compnr [varchar](10) NULL,
	sfbp [varchar](9) NULL,
	sfbp_ref_compnr [varchar](10) NULL,
	sfcn [varchar](9) NULL,
	sfcn_ref_compnr [varchar](10) NULL,
	srcn [varchar](9) NULL,
	ztimestamp [datetime] NULL,
	trid [varchar](9) NULL,
	trid_ref_compnr [varchar](10) NULL,
	txta [int] NULL,
	txta_ref_compnr [varchar](10) NULL,
	txtb [int] NULL,
	txtb_ref_compnr [varchar](10) NULL,
	txtt [int] NULL,
	txtt_ref_compnr [varchar](10) NULL,
	username [varchar](8) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (cono)
)
GO

/**********************************************************************************************************************
Table Name: [acq101].[dst_tdpur411]
Description: This is a DST table for Accounts Payable Purchase Order Line Item Data

Data Type: Transaction Data

Original Project: JBT Finance Account Payable & Purchasing
Developer: Mohammed Majid
Date: 07/07/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [acq101].[dst_tdpur411];

CREATE TABLE [acq101].[dst_tdpur411] 
(
	citg [varchar](6) NULL,
	citg_ref_compnr [varchar](10) NULL,
	compnr [varchar](10) NOT NULL,
	cpcl [varchar](6) NULL,
	cpcl_ref_compnr [varchar](10) NULL,
	cpgp [varchar](6) NULL,
	cpgp_ref_compnr [varchar](10) NULL,
	cpln [varchar](6) NULL,
	cpln_ref_compnr [varchar](10) NULL,
	csgp [varchar](6) NULL,
	csgp_ref_compnr [varchar](10) NULL,
	deleted [varchar](10) NULL,
	item [varchar](47) NULL,
	item_ref_compnr [varchar](10) NULL,
	iwgt [float] NULL,
	iwun [varchar](3) NULL,
	iwun_ref_compnr [varchar](10) NULL,
	kitm [int] NULL,
	kitm_kw [varchar](255) NULL,
	orno [varchar](9) NOT NULL,
	orno_pono_sqnb_ref_compnr [varchar](10) NULL,
	orno_ref_compnr [varchar](10) NULL,
	pgmd [int] NULL,
	pgmd_kw [varchar](255) NULL,
	pono [int] NOT NULL,
	prtp [varchar](3) NULL,
	prtp_ref_compnr [varchar](10) NULL,
	sequencenumber [int] NULL,
	sqnb [int] NOT NULL,
	ztimestamp [datetime] NULL,
	username [varchar](8) NULL,
	file_name [varchar](100) NOT NULL,
	dwh_load_time [datetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH (pono)
)
GO
