/**********************************************************************************************************************
Table Name: [replncss].[fct Sales Revenue Cube]
This Fact clone cube is created by joining the Fact Sales Revenue View & Dim Views which is exposed to the Tableau for Dashboard Build.

Data Type: Fact Data
Original Project: JBT Sales
Developer: Mohammed Majid
Date: 18/05/2021
Reviewed By: Atul Raje

Change History:N/A
Dt: 18/06/2021
Added New fields ([Default Supply Source By Site],[Default Supply Source By Site Desc],[Ship-to State/Province],[Ship-to City Name],[Sold-to State/Province],[Sold-to City Name]) which are required for Reporting.

Dt:05/08/2021
Added New fields (Ship-to Address Desc,Sold-to Address Desc) which are required for Reporting.

Dt:17/08/2021
Added New fields (Latitude,Longitde,Territory) which are required for Reporting.

Dt:18/08/2021
Added "[Ship Constraint Desc]" field for Sales order lines table as part of report requirement.

Dt:15/09/2021
Added "[Requested Duration Days]" field in Sales Revenue cube as part of report requirement.

**********************************************************************************************************************/
--Drop Table [replncss].[fct Sales Revenue Cube]

CREATE TABLE [replncss].[fct Sales Revenue Cube]
(
	[Line Disc Amt] [float] NOT NULL,
	[SO Blocked] [int] NULL,
	[Canceled] [int] NULL,
	[Contract] [varchar](9) NULL,
	[Cust Order] [varchar](255) NULL,
	[Change Reason] [varchar](6) NULL,
	[BackOrd UoM] [varchar](3) NULL,
	[Warehouse] [varchar](6) NULL,
	[Plnd Deliv Date] [date] NULL,
	[Init Req Date] [date] NULL,
	[Cust Req Date] [date] NULL,
	[Orig Deliv Date] [date] NULL,
	[Delivery Date] [date] NULL,
	[SO Order Date] [date] NULL,
	[Sales Lines] [int] NULL,
	[Plnd Receipt Date] [date] NULL,
	[Price] [float] NOT NULL,
	[SO Delivered Qty] [float] NOT NULL,
	[Ordered Qty] [float] NOT NULL,
	[Exch Rate Type] [varchar](3) NULL,
	[Ship Constraint] [int] NULL,
	[Supply-from Whs] [varchar](6) NULL,
	[So Shipment] [varchar](9) NULL,
	[Line Sequence] [int] NULL,
	[Ship-to Whs] [varchar](6) NULL,
	[Ext Sales Rep] [varchar](9) NULL,
	[Return Reason] [varchar](6) NULL,
	[Sales Ord Type] [varchar](3) NULL,
	[Reference A] [int] NULL,
	[Sales Price List] [varchar](3) NULL,
	[Plan Deliv Date] [date] NULL,
	[Installments] [int] NULL,
	[SO Order Status] [int] NULL,
	[Cost Serv Cont] [float] NOT NULL,
	[Cost FCO] [float] NOT NULL,
	[Cost SO Inv] [float] NOT NULL,
	[Activity Line] [int] NULL,
	[Cost Goodwill] [float] NOT NULL,
	[Act Unit Cost] [float] NOT NULL,
	[Cost Quote] [float] NOT NULL,
	[Actual Line] [int] NULL,
	[Cost Warranty] [float] NOT NULL,
	[Actual Cum Qty] [float] NOT NULL,
	[Actual Del Tme] [datetime] NULL,
	[Total Cost] [float] NOT NULL,
	[Ord Disc Amt] [float] NOT NULL,
	[Act Purch Amt] [float] NOT NULL,
	[Sales Serv Con] [float] NOT NULL,
	[Total Disc Amt] [float] NOT NULL,
	[Sales FCO] [float] NOT NULL,
	[Sales SO Inv] [float] NOT NULL,
	[Sales Goodwill] [float] NOT NULL,
	[Sales Amt Quote] [float] NOT NULL,
	[Total Sales Amt] [float] NOT NULL,
	[Sales Warranty] [float] NOT NULL,
	[MC Blocked] [int] NULL,
	[Tax Classif] [varchar](12) NULL,
	[Delivery Terms] [varchar](3) NULL,
	[Discount Code] [varchar](3) NULL,
	[Carrier] [varchar](3) NULL,
	[Cost Line Stat] [int] NULL,
	[Company number] [varchar](10) NOT NULL,
	[Contr Converage] [int] NULL,
	[Sales Price Unit] [varchar](3) NULL,
	[Sales Qty Unit] [varchar](3) NULL,
	[Delivery Code] [varchar](6) NULL,
	[SO Discount] [float] NOT NULL,
	[Delivery Type] [int] NULL,
	[Est Unit Cost] [float] NOT NULL,
	[Service Est Qty] [float] NOT NULL,
	[Service Est Cost Line] [int] NOT NULL,
	[Est Sales Price] [float] NOT NULL,
	[Items] [varchar](47) NULL,
	[MC Residual Value] [float] NOT NULL,
	[Discount Amt] [float] NOT NULL,
	[Other Lines] [int] NULL,
	[Service Order] [varchar](9) NULL,
	[Activity] [varchar](16) NULL,
	[Material or Maintenance Items] [varchar](47) NULL,
	[Price Origin] [int] NULL,
	[Sales Price] [float] NOT NULL,
	[PoTP] [varchar](9) NULL,
	[Required Qty] [float] NOT NULL,
	[Cost Repair War] [float] NOT NULL,
	[Sales Repair War] [float] NOT NULL,
	[Repair Warranty] [int] NULL,
	[Ship Matl To] [int] NULL,
	[Line of Business] [varchar](6) NULL,
	[Payment Terms] [varchar](3) NULL,
	[Sales Rep] [varchar](9) NULL,
	[Financial Dept] [varchar](6) NULL,
	[Invoice-to Addr] [varchar](9) NULL,
	[Invoice-to BP] [varchar](9) NULL,
	[Sold-to Address] [varchar](9) NULL,
	[Sold-to BP] [varchar](9) NULL,
	[Payment Method] [varchar](3) NULL,
	[Rate Type] [varchar](3) NULL,
	[SvcO Cost Sheet] [varchar](9) NULL,
	[Act Order Amt] [float] NOT NULL,
	[SOC Cancel Date] [varchar](10) NULL,
	[Coverage Type] [varchar](3) NULL,
	[Currency] [varchar](3) NULL,
	[Serv Contract] [varchar](9) NULL,
	[Service Type] [varchar](3) NULL,
	[Service Office] [varchar](6) NULL,
	[Est Order Amt] [float] NOT NULL,
	[Pricing Method] [int] NULL,
	[Plan Start Time] [datetime] NULL,
	[Warranty Type] [int] NULL,
	[Act Cost Rate] [float] NOT NULL,
	[Labor Type Cost] [varchar](3) NULL,
	[Labor Rate Code] [varchar](6) NULL,
	[Task] [varchar](8) NULL,
	[Service Discount] [float] NOT NULL,
	[Est Cost rate] [float] NOT NULL,
	[Labor Est Qty] [float] NOT NULL,
	[Sales Inv Amt] [float] NOT NULL,
	[Sales Inv Date] [datetime] NULL,
	[Labor Type Sales] [varchar](3) NULL,
	[Service Warranty] [int] NULL,
	[Cost Amt War] [float] NOT NULL,
	[Actual Qty] [float] NOT NULL,
	[Cost Type] [int] NULL,
	[Unit] [varchar](3) NULL,
	[Est Cost Line Id] [varchar](22) NULL,
	[Other Costs Items] [varchar](47) NULL,
	[Act Receipt Time] [datetime] NULL,
	[Maint SO] [varchar](9) NULL,
	[Planned Carrier 1] [varchar](3) NULL,
	[Item Delivery] [int] NULL,
	[MO Delivered Qty] [float] NOT NULL,
	[Delivery Whse] [varchar](6) NULL,
	[MO Line Status] [int] NULL,
	[Order Discount] [float] NULL,
	[Non SO Plan Deliv Date] [datetime] NULL,
	[Plan Rec Time] [datetime] NULL,
	[Qty] [float] NOT NULL,
	[Actual Carrier] [varchar](3) NULL,
	[Planned Carrier 2] [varchar](3) NULL,
	[Received Qty] [float] NOT NULL,
	[Shipment] [varchar](9) NULL,
	[Receipt Whse] [varchar](6) NULL,
	[Ship-to Address] [varchar](9) NULL,
	[Ship-to BP] [varchar](9) NULL,
	[Sales Type] [varchar](6) NULL,
	[Work Order Num] [varchar](9) NULL,
	[MO Warranty] [varchar](16) NULL,
	[Desc] [varchar](255) NULL,
	[Installment Plan] [varchar](9) NULL,
	[MO Order Date] [datetime] NULL,
	[MO Order Status] [int] NULL,
	[Amt Dom Curr] [float] NOT NULL,
	[Net Amt] [float] NOT NULL,
	[Tax Code] [varchar](9) NULL,
	[Manual Sales ID] [varchar](9) NULL,
	[Manual Lines] [int] NULL,
	[Financial Comp] [int] NULL,
	[Tax Amt Dom] [float] NOT NULL,
	[Department] [varchar](6) NULL,
	[Approved Amt] [float] NOT NULL,
	[Approval Action] [int] NULL,
	[Approved By] [varchar](16) NULL,
	[Approval Desci] [varchar](6) NULL,
	[Approval Date] [datetime] NULL,
	[Approval Percent] [float] NULL,
	[Claim] [varchar](9) NULL,
	[Claimed Amt] [float] NOT NULL,
	[Claim Method] [int] NULL,
	[Appr Qty Unit] [varchar](3) NULL,
	[Claim Qty Unit] [varchar](3) NULL,
	[CC Residual Value] [float] NOT NULL,
	[Sales Doc Line] [int] NULL,
	[Sales Doc Seq] [int] NULL,
	[Approved Qty] [float] NOT NULL,
	[Claimed Qty] [float] NOT NULL,
	[Reject Action] [int] NULL,
	[Rejected By] [varchar](16) NULL,
	[Rejection Date] [datetime] NULL,
	[Reject Reasons] [varchar](6) NULL,
	[Return Matl Req] [int] NULL,
	[CC Line Status] [int] NULL,
	[Tagged To] [int] NULL,
	[Wait Supp Claim] [int] NULL,
	[CC Cancel Date] [datetime] NULL,
	[Creation Date] [datetime] NULL,
	[Failure Date] [datetime] NULL,
	[Int Sales Rep] [varchar](9) NULL,
	[Sales Inv Comp] [int] NULL,
	[Sales Doc Num] [varchar](9) NULL,
	[Sales Doc Type] [int] NULL,
	[Sales Ref Sys] [int] NULL,
	[Created by] [varchar](16) NULL,
	[Order Number] [varchar](9) NOT NULL,
	[Order Line Numb] [varchar](20) NOT NULL,
	[Table Desc] [varchar](100) NOT NULL,
	[Table Shortcode] [varchar](10) NOT NULL,
	[Remain Order Qty] [float] NOT NULL,
	[Order Value Due] [float] NOT NULL,
	[NetLineAmt Dom] [float] NOT NULL,
	[Delivery Note] [varchar](19) NULL,
	[Invoice Number] [int] NULL,
	[Produc Relation] [varchar](255) NULL,
	[Shipment Line] [int] NULL,
	[Source Type] [int] NULL,
	[Time of Action] [datetime] NULL,
	[Inv Trans Type] [varchar](3) NULL,
	[INV Delivered Qty] [float] NULL,
	[Inv Line Seq] [int] NULL,
	[Area] [varchar](3) NULL,
	[Carrier/LSP Desc] [varchar](255) NULL,
	[Deleted Record] [varchar](10) NULL,
	[Carrier Alpha Code] [varchar](20) NULL,
	[Buy-from Business Partner] [varchar](9) NULL,
	[Transport Category] [int] NULL,
	[Transport Category Desc] [varchar](255) NULL,
	[Change Reason Desc] [varchar](255) NULL,
	[Last Inventory Transaction Date] [datetime] NULL,
	[Inventory Allocated] [float] NULL,
	[Inventory Blocked] [float] NULL,
	[Inventory Blocked for Planning] [float] NULL,
	[Consignment Inventory Location Allocated] [float] NULL,
	[Consignment Inventory on Hand] [float] NULL,
	[Cumulative Issue] [float] NULL,
	[Consignment Inventory in Transit] [float] NULL,
	[Inventory Committed] [float] NULL,
	[Consignment on Order] [float] NULL,
	[Inventory Committed in Process] [float] NULL,
	[Consigned Quarantine] [float] NULL,
	[Goods in Transit] [float] NULL,
	[Historical Balance] [float] NULL,
	[Inventory on Hand] [float] NULL,
	[Company Owned Quarantine Inventory] [float] NULL,
	[Inventory in Transit] [float] NULL,
	[Inventory Location Allocated] [float] NULL,
	[Cust Owned Location Allocated] [float] NULL,
	[Cust Owned Blocked] [float] NULL,
	[Cust Owned Blocked for Planning] [float] NULL,
	[Cust Owned on Hand] [float] NULL,
	[Cust Owned in Transit] [float] NULL,
	[Cust Owned on Order] [float] NULL,
	[Cust Owned Quarantine] [float] NULL,
	[Comp Owned Location Allocated] [float] NULL,
	[Comp Owned on Order] [float] NULL,
	[Inventory on Order] [float] NULL,
	[Items Desc] [varchar](255) NULL,
	[Item Group] [varchar](6) NULL,
	[Product Class] [varchar](6) NULL,
	[Product Line] [varchar](6) NULL,
	[Item Signal] [varchar](3) NULL,
	[Country of Origin] [varchar](3) NULL,
	[Product Type] [varchar](3) NULL,
	[Inventory Unit] [varchar](3) NULL,
	[Serialized] [int] NULL,
	[Default Supply Source] [int] NULL,
	[Line of Business Desc] [varchar](255) NULL,
	[Sales Office Desc] [varchar](255) NULL,
	[Site] [varchar](9) NULL,
	[Sales Order Type Desc] [varchar](255) NULL,
	[Ship-to Address Code] [varchar](9) NULL,
	[Ship-to Country] [varchar](50) NULL,
	[Ship-to Country Name] [varchar](100) NULL,
	[Ship-to BP Name] [varchar](255) NULL,
	[Sold-to Address Code] [varchar](9) NULL,
	[Sold-to Country] [varchar](50) NULL,
	[Sold-to Country Name] [varchar](100) NULL,
	[Sold-to BP Name] [varchar](255) NULL,
	[Tax Classification Desc] [varchar](255) NULL,
	[Max W/Tax %] [float] NULL,
	[SCT Allowed] [int] NULL,
	[SCT Allowed Falg] [varchar](255) NULL,
	[WIT Allowed] [int] NULL,
	[WIT Allowed Flag] [varchar](255) NULL,
	[Warehouse Desc] [varchar](255) NULL,
	[Warehouse Address Code] [varchar](9) NULL,
	[Financial Company] [int] NULL,
	[Enterprise unit of Wh] [varchar](6) NULL,
	[Inventory Mgt Business Partner] [varchar](9) NULL,
	[External Site] [int] NULL,
	[External Site Flag] [varchar](255) NULL,
	[Delivery Duration Days] [int] NULL,
	[Delivery Days against Plan] [int] NULL,
	[Delivery Days against Cust Req] [int] NULL,
	[Late To Plan Flag] [int] NULL,
	[Late To Cust Req Flag] [int] NULL,
	[Completed Delivery Flag] [int] NOT NULL,
	[On-Going Delivery Flag] [int] NOT NULL,
	[Late Orders Flag] [int] NULL,
	[Product Line Levels] [int] NULL,
	[Product Line First Level] [varchar](255) NULL,
	[Product Line Second Level] [varchar](255) NULL,
	[Product Line Third Level] [varchar](255) NULL,
	[Department Desc] [varchar](255) NULL,
	[Department Site] [varchar](9) NULL,
	[Department Type Key] [int] NULL,
	[Department Type] [varchar](255) NULL,
	[Ship-to Region] [varchar](50) NULL,
	[Ship-to Sub Region] [varchar](100) NULL,
	[Sold-to Region] [varchar](50) NULL,
	[Sold-to Sub Region] [varchar](100) NULL,
	[Back Order Qty] [float] NOT NULL,
	[Original Ordered Qty] [float] NOT NULL,
	[SO Order Status Desc] [varchar](255) NULL,
	[On-Time Flag] [int] NULL,
	[Ship-to State/Province] [varchar](3) NULL,
	[Ship-to City Name] [varchar](255) NULL,
	[Sold-to State/Province] [varchar](3) NULL,
	[Sold-to City Name] [varchar](255) NULL,
	[Default Supply Source By Site] [int] NULL,
	[Default Supply Source By Site Desc] [varchar](255) NULL,
	[Delivered Value] [float] NULL,
	[SO Aval In Invoice Table Flag] [char](1) NULL,
	[NetLineAmt Dom Prop] [float] NULL,
	[INV Delivered Qty Prop] [float] NULL,
	[SO Invoiced Flag] [char](1) NULL,
	[Pending Qty for Delivery] [float] NULL,
	[Shipped but not Invoiced] [float] NULL,
	[DWH Load Time] [datetime] NOT NULL,
	[Reporting Date] [date] NULL,
	[Blocked for Inbound] 	 	[int] NULL,
	[Blocked for Inbound Desc] 	[varchar](255) NULL,
	[Blocked for Outbound]	 	[int] NULL,
	[Blocked for Outbound  Desc]  [varchar](255) NULL,
	[Ship-to Address Desc] [varchar](255) NULL,
	[Sold-to Address Desc] [varchar](255) NULL,
	[Sold-to Latitude] [float] NULL,
	[Sold-to Longitude] [float] NULL,
	[Sold-to Territory]	[varchar](255) NULL,
	[Ship-to Latitude] [float] NULL,
	[Ship-to Longitude] [float] NULL,
	[Ship-to Territory]	[varchar](255) NULL,
	[Ship Constraint Desc] [varchar](255) NULL,
	[Requested Duration Days] [int] NULL,
	[Items Type] [varchar](50) NULL,
	[OTD Plan Deliv Date Flag] [int] NULL,
	[OTD Orig Prom Deliv Date Flag] [int] NULL, 
	[OTD Cust Req Deliv Date Flag] [int] NULL,
	[Delivery Days against Orig Prom] [int] NULL,
	[Late To Init Req Flag] [int] NULL,
	[Late To Orig Deliv Flag] [int] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Order Line Numb] )
)
GO


/**********************************************************************************************************************
Table Name: [replncss].[fct History Sales Revenue Cube]
This Fact clone cube is created by joining the Fact History Sales Revenue View & Dim Views which is exposed to the Tableau for Dashboard Build.

Data Type: Fact Data
Original Project: JBT Sales
Developer: Mohammed Majid
Date: 17/06/2021
Reviewed By: Atul Raje

Change History:N/A

Dt:05/08/2021
Added New fields (Ship-to Address Desc,Sold-to Address Desc,History Action) which are required for Reporting.

Dt:17/08/2021
Added New fields (Latitude,Longitde,Territory) which are required for Reporting.

**********************************************************************************************************************/
--Drop Table [replncss].[fct History Sales Revenue Cube]

CREATE TABLE [replncss].[fct History Sales Revenue Cube]
(
	[Line Disc Amt] [float] NOT NULL,
	[SO Blocked] [int] NULL,
	[Canceled] [int] NULL,
	[Contract] [varchar](9) NULL,
	[Cust Order] [varchar](255) NULL,
	[Change Reason] [varchar](6) NULL,
	[BackOrd UoM] [varchar](3) NULL,
	[Warehouse] [varchar](6) NULL,
	[Plnd Deliv Date] [date] NULL,
	[Init Req Date] [date] NULL,
	[Cust Req Date] [date] NULL,
	[Orig Deliv Date] [date] NULL,
	[SO Order Date] [date] NULL,
	[Sales Lines] [int] NULL,
	[Plnd Receipt Date] [date] NULL,
	[Price] [float] NOT NULL,
	[SO Delivered Qty] [float] NOT NULL,
	[Ordered Qty] [float] NOT NULL,
	[Exch Rate Type] [varchar](3) NULL,
	[Ship Constraint] [int] NULL,
	[Supply-from Whs] [varchar](6) NULL,
	[So Shipment] [varchar](9) NULL,
	[Line Sequence] [int] NULL,
	[Ship-to Whs] [varchar](6) NULL,
	[Ext Sales Rep] [varchar](9) NULL,
	[Return Reason] [varchar](6) NULL,
	[Sales Ord Type] [varchar](3) NULL,
	[Reference A] [int] NULL,
	[Sales Price List] [varchar](3) NULL,
	[Plan Deliv Date] [date] NULL,
	[Installments] [int] NULL,
	[SO Order Status] [int] NULL,
	[Cost Serv Cont] [float] NOT NULL,
	[Cost FCO] [float] NOT NULL,
	[Cost SO Inv] [float] NOT NULL,
	[Activity Line] [int] NULL,
	[Cost Goodwill] [float] NOT NULL,
	[Act Unit Cost] [float] NOT NULL,
	[Cost Quote] [float] NOT NULL,
	[Actual Line] [int] NULL,
	[Cost Warranty] [float] NOT NULL,
	[Actual Cum Qty] [float] NOT NULL,
	[Actual Del Tme] [datetime] NULL,
	[Total Cost] [float] NOT NULL,
	[Ord Disc Amt] [float] NOT NULL,
	[Act Purch Amt] [float] NOT NULL,
	[Sales Serv Con] [float] NOT NULL,
	[Total Disc Amt] [float] NOT NULL,
	[Sales FCO] [float] NOT NULL,
	[Sales SO Inv] [float] NOT NULL,
	[Sales Goodwill] [float] NOT NULL,
	[Sales Amt Quote] [float] NOT NULL,
	[Total Sales Amt] [float] NOT NULL,
	[Sales Warranty] [float] NOT NULL,
	[MC Blocked] [int] NULL,
	[Tax Classif] [varchar](12) NULL,
	[Delivery Terms] [varchar](3) NULL,
	[Discount Code] [varchar](3) NULL,
	[Carrier] [varchar](3) NULL,
	[Cost Line Stat] [int] NULL,
	[Company number] [varchar](10) NOT NULL,
	[Contr Converage] [int] NULL,
	[Sales Price Unit] [varchar](3) NULL,
	[Sales Qty Unit] [varchar](3) NULL,
	[Delivery Code] [varchar](6) NULL,
	[SO Discount] [float] NOT NULL,
	[Delivery Type] [int] NULL,
	[Est Unit Cost] [float] NOT NULL,
	[Service Est Qty] [float] NOT NULL,
	[Service Est Cost Line] [int] NOT NULL,
	[Est Sales Price] [float] NOT NULL,
	[Items] [varchar](47) NULL,
	[MC Residual Value] [float] NOT NULL,
	[Discount Amt] [float] NOT NULL,
	[Other Lines] [int] NULL,
	[Service Order] [varchar](9) NULL,
	[Activity] [varchar](16) NULL,
	[Material or Maintenance Items] [varchar](47) NULL,
	[Price Origin] [int] NULL,
	[Sales Price] [float] NOT NULL,
	[PoTP] [varchar](9) NULL,
	[Required Qty] [float] NOT NULL,
	[Cost Repair War] [float] NOT NULL,
	[Sales Repair War] [float] NOT NULL,
	[Repair Warranty] [int] NULL,
	[Ship Matl To] [int] NULL,
	[Line of Business] [varchar](6) NULL,
	[Payment Terms] [varchar](3) NULL,
	[Sales Rep] [varchar](9) NULL,
	[Financial Dept] [varchar](6) NULL,
	[Invoice-to Addr] [varchar](9) NULL,
	[Invoice-to BP] [varchar](9) NULL,
	[Sold-to Address] [varchar](9) NULL,
	[Sold-to BP] [varchar](9) NULL,
	[Payment Method] [varchar](3) NULL,
	[Rate Type] [varchar](3) NULL,
	[SvcO Cost Sheet] [varchar](9) NULL,
	[Act Order Amt] [float] NOT NULL,
	[SOC Cancel Date] [varchar](10) NULL,
	[Coverage Type] [varchar](3) NULL,
	[Currency] [varchar](3) NULL,
	[Serv Contract] [varchar](9) NULL,
	[Service Type] [varchar](3) NULL,
	[Service Office] [varchar](6) NULL,
	[Est Order Amt] [float] NOT NULL,
	[Pricing Method] [int] NULL,
	[Plan Start Time] [datetime] NULL,
	[Warranty Type] [int] NULL,
	[Act Cost Rate] [float] NOT NULL,
	[Labor Type Cost] [varchar](3) NULL,
	[Labor Rate Code] [varchar](6) NULL,
	[Task] [varchar](8) NULL,
	[Service Discount] [float] NOT NULL,
	[Est Cost rate] [float] NOT NULL,
	[Labor Est Qty] [float] NOT NULL,
	[Sales Inv Amt] [float] NOT NULL,
	[Sales Inv Date] [datetime] NULL,
	[Labor Type Sales] [varchar](3) NULL,
	[Service Warranty] [int] NULL,
	[Cost Amt War] [float] NOT NULL,
	[Actual Qty] [float] NOT NULL,
	[Cost Type] [int] NULL,
	[Unit] [varchar](3) NULL,
	[Est Cost Line Id] [varchar](22) NULL,
	[Other Costs Items] [varchar](47) NULL,
	[Act Receipt Time] [datetime] NULL,
	[Maint SO] [varchar](9) NULL,
	[Planned Carrier 1] [varchar](3) NULL,
	[Item Delivery] [int] NULL,
	[MO Delivered Qty] [float] NOT NULL,
	[Delivery Whse] [varchar](6) NULL,
	[MO Line Status] [int] NULL,
	[Order Discount] [float] NULL,
	[Non SO Plan Deliv Date] [datetime] NULL,
	[Plan Rec Time] [datetime] NULL,
	[Qty] [float] NOT NULL,
	[Actual Carrier] [varchar](3) NULL,
	[Planned Carrier 2] [varchar](3) NULL,
	[Received Qty] [float] NOT NULL,
	[Shipment] [varchar](9) NULL,
	[Receipt Whse] [varchar](6) NULL,
	[Ship-to Address] [varchar](9) NULL,
	[Ship-to BP] [varchar](9) NULL,
	[Sales Type] [varchar](6) NULL,
	[Work Order Num] [varchar](9) NULL,
	[MO Warranty] [varchar](16) NULL,
	[Desc] [varchar](255) NULL,
	[Installment Plan] [varchar](9) NULL,
	[MO Order Date] [datetime] NULL,
	[MO Order Status] [int] NULL,
	[Amt Dom Curr] [float] NOT NULL,
	[Net Amt] [float] NOT NULL,
	[Tax Code] [varchar](9) NULL,
	[Manual Sales ID] [varchar](9) NULL,
	[Manual Lines] [int] NULL,
	[Financial Comp] [int] NULL,
	[Tax Amt Dom] [float] NOT NULL,
	[Department] [varchar](6) NULL,
	[Approved Amt] [float] NOT NULL,
	[Approval Action] [int] NULL,
	[Approved By] [varchar](16) NULL,
	[Approval Desci] [varchar](6) NULL,
	[Approval Date] [datetime] NULL,
	[Approval Percent] [float] NULL,
	[Claim] [varchar](9) NULL,
	[Claimed Amt] [float] NOT NULL,
	[Claim Method] [int] NULL,
	[Appr Qty Unit] [varchar](3) NULL,
	[Claim Qty Unit] [varchar](3) NULL,
	[CC Residual Value] [float] NOT NULL,
	[Sales Doc Line] [int] NULL,
	[Sales Doc Seq] [int] NULL,
	[Approved Qty] [float] NOT NULL,
	[Claimed Qty] [float] NOT NULL,
	[Reject Action] [int] NULL,
	[Rejected By] [varchar](16) NULL,
	[Rejection Date] [datetime] NULL,
	[Reject Reasons] [varchar](6) NULL,
	[Return Matl Req] [int] NULL,
	[CC Line Status] [int] NULL,
	[Tagged To] [int] NULL,
	[Wait Supp Claim] [int] NULL,
	[CC Cancel Date] [datetime] NULL,
	[Creation Date] [datetime] NULL,
	[Failure Date] [datetime] NULL,
	[Int Sales Rep] [varchar](9) NULL,
	[Sales Inv Comp] [int] NULL,
	[Sales Doc Num] [varchar](9) NULL,
	[Sales Doc Type] [int] NULL,
	[Sales Ref Sys] [int] NULL,
	[Created by] [varchar](16) NULL,
	[Order Number] [varchar](9) NOT NULL,
	[Order Line Numb] [varchar](20) NOT NULL,
	[Table Desc] [varchar](100) NOT NULL,
	[Table Shortcode] [varchar](10) NOT NULL,
	[Remain Order Qty] [float] NOT NULL,
	[Order Value Due] [float] NOT NULL,
	[NetLineAmt Dom] [float] NOT NULL,
	[Delivery Note] [varchar](19) NULL,
	[Invoice Number] [int] NULL,
	[Produc Relation] [varchar](255) NULL,
	[Shipment Line] [int] NULL,
	[Source Type] [int] NULL,
	[Time of Action] [datetime] NULL,
	[Inv Trans Type] [varchar](3) NULL,
	[INV Delivered Qty] [float] NULL,
	[Inv Line Seq] [int] NULL,
	[Area] [varchar](3) NULL,
	[Carrier/LSP Desc] [varchar](255) NULL,
	[Deleted Record] [varchar](10) NULL,
	[Carrier Alpha Code] [varchar](20) NULL,
	[Buy-from Business Partner] [varchar](9) NULL,
	[Transport Category] [int] NULL,
	[Transport Category Desc] [varchar](255) NULL,
	[Change Reason Desc] [varchar](255) NULL,
	[Last Inventory Transaction Date] [datetime] NULL,
	[Inventory Allocated] [float] NULL,
	[Inventory Blocked] [float] NULL,
	[Inventory Blocked for Planning] [float] NULL,
	[Consignment Inventory Location Allocated] [float] NULL,
	[Consignment Inventory on Hand] [float] NULL,
	[Cumulative Issue] [float] NULL,
	[Consignment Inventory in Transit] [float] NULL,
	[Inventory Committed] [float] NULL,
	[Consignment on Order] [float] NULL,
	[Inventory Committed in Process] [float] NULL,
	[Consigned Quarantine] [float] NULL,
	[Goods in Transit] [float] NULL,
	[Historical Balance] [float] NULL,
	[Inventory on Hand] [float] NULL,
	[Company Owned Quarantine Inventory] [float] NULL,
	[Inventory in Transit] [float] NULL,
	[Inventory Location Allocated] [float] NULL,
	[Cust Owned Location Allocated] [float] NULL,
	[Cust Owned Blocked] [float] NULL,
	[Cust Owned Blocked for Planning] [float] NULL,
	[Cust Owned on Hand] [float] NULL,
	[Cust Owned in Transit] [float] NULL,
	[Cust Owned on Order] [float] NULL,
	[Cust Owned Quarantine] [float] NULL,
	[Comp Owned Location Allocated] [float] NULL,
	[Comp Owned on Order] [float] NULL,
	[Inventory on Order] [float] NULL,
	[Items Desc] [varchar](255) NULL,
	[Item Group] [varchar](6) NULL,
	[Product Class] [varchar](6) NULL,
	[Product Line] [varchar](6) NULL,
	[Item Signal] [varchar](3) NULL,
	[Country of Origin] [varchar](3) NULL,
	[Product Type] [varchar](3) NULL,
	[Inventory Unit] [varchar](3) NULL,
	[Serialized] [int] NULL,
	[Default Supply Source] [int] NULL,
	[Line of Business Desc] [varchar](255) NULL,
	[Sales Office Desc] [varchar](255) NULL,
	[Site] [varchar](9) NULL,
	[Sales Order Type Desc] [varchar](255) NULL,
	[Ship-to Address Code] [varchar](9) NULL,
	[Ship-to Country] [varchar](50) NULL,
	[Ship-to Country Name] [varchar](100) NULL,
	[Ship-to BP Name] [varchar](255) NULL,
	[Sold-to Address Code] [varchar](9) NULL,
	[Sold-to Country] [varchar](50) NULL,
	[Sold-to Country Name] [varchar](100) NULL,
	[Sold-to BP Name] [varchar](255) NULL,
	[Tax Classification Desc] [varchar](255) NULL,
	[Max W/Tax %] [float] NULL,
	[SCT Allowed] [int] NULL,
	[SCT Allowed Falg] [varchar](255) NULL,
	[WIT Allowed] [int] NULL,
	[WIT Allowed Flag] [varchar](255) NULL,
	[Warehouse Desc] [varchar](255) NULL,
	[Warehouse Address Code] [varchar](9) NULL,
	[Financial Company] [int] NULL,
	[Enterprise unit of Wh] [varchar](6) NULL,
	[Inventory Mgt Business Partner] [varchar](9) NULL,
	[External Site] [int] NULL,
	[External Site Flag] [varchar](255) NULL,
	[Completed Delivery Flag] [int] NOT NULL,
	[On-Going Delivery Flag] [int] NOT NULL,
	[Late Orders Flag] [int] NULL,
	[Product Line Levels] [int] NULL,
	[Product Line First Level] [varchar](255) NULL,
	[Product Line Second Level] [varchar](255) NULL,
	[Product Line Third Level] [varchar](255) NULL,
	[Department Desc] [varchar](255) NULL,
	[Department Site] [varchar](9) NULL,
	[Department Type Key] [int] NULL,
	[Department Type] [varchar](255) NULL,
	[Ship-to Region] [varchar](50) NULL,
	[Ship-to Sub Region] [varchar](100) NULL,
	[Sold-to Region] [varchar](50) NULL,
	[Sold-to Sub Region] [varchar](100) NULL,
	[Back Order Qty] [float] NOT NULL,
	[Original Ordered Qty] [float] NOT NULL,
	[SO Order Status Desc] [varchar](255) NULL,
	[Ord Changed Amt] [float] NOT NULL,
	[SO Record Type] [int] NULL,
	[SO Sequence Number] [int] NULL,
	[SO Transaction Date] [date] NULL,
	[SO Transaction Datetime] [datetime] NULL,
	[Ship-to State/Province] [varchar](3) NULL,
	[Ship-to City Name] [varchar](255) NULL,
	[Sold-to State/Province] [varchar](3) NULL,
	[Sold-to City Name] [varchar](255) NULL,
	[Default Supply Source By Site] [int] NULL,
	[Default Supply Source By Site Desc] [varchar](255) NULL,
	[Delivered Value] [float] NULL,
	[DWH Load Time] [datetime] NOT NULL,
	[Reporting Date] [date] NULL,
	[Delivery Date] [date] NULL,
	[Blocked for Inbound] 	 	[int] NULL,
	[Blocked for Inbound Desc] 	[varchar](255) NULL,
	[Blocked for Outbound]	 	[int] NULL,
	[Blocked for Outbound  Desc]  [varchar](255) NULL,
	[Ship-to Address Desc] [varchar](255) NULL,
	[Sold-to Address Desc] [varchar](255) NULL,
	[History Action] [int] NULL,
	[Sold-to Latitude] [float] NULL,
	[Sold-to Longitude] [float] NULL,
	[Sold-to Territory]	[varchar](255) NULL,
	[Ship-to Latitude] [float] NULL,
	[Ship-to Longitude] [float] NULL,
	[Ship-to Territory]	[varchar](255) NULL,
	[Ship Constraint Desc] [varchar](255) NULL,
	[Items Type] [varchar](50) NULL
)
WITH
(
	DISTRIBUTION = HASH ( [SO Sequence Number] )
)
GO

/**********************************************************************************************************************
Table Name: [replncss].[CDW fct Sales Order Act Delivery Lines Cube]
This Fact clone cube is created by joining the Fact Sales Revenue View & Dim Views which is exposed to the Tableau for Dashboard Build.

Data Type: Fact Data
Original Project: JBT Sales
Developer: Mohammed Majid
Date: 08/09/2021
Reviewed By: Atul Raje

Change History:N/A

**********************************************************************************************************************/
--Drop Table [replncss].[CDW fct Sales Order Act Delivery Lines Cube]

CREATE TABLE [replncss].[CDW fct Sales Order Act Delivery Lines Cube]
(
	[Line Disc Amt] [float] NOT NULL,
	[SO Blocked] [int] NULL,
	[Canceled] [int] NULL,
	[Contract] [varchar](9) NULL,
	[Cust Order] [varchar](255) NULL,
	[Change Reason] [varchar](6) NULL,
	[BackOrd UoM] [varchar](3) NULL,
	[Warehouse] [varchar](6) NULL,
	[Init Req Date] [date] NULL,
	[Cust Req Date] [date] NULL,
	[Orig Deliv Date] [date] NULL,
	[Delivery Datetime] [datetime] NULL,
	[Delivery Date] [date] NULL,
	[SO Order Date] [date] NULL,
	[Plnd Receipt Date] [date] NULL,
	[Plan Deliv Date] [date] NULL,
	[Sales Inv Date] [date] NULL,
	[Sales Lines] [int] NOT NULL,
	[Price] [float] NOT NULL,
	[SO Delivered Qty] [float] NOT NULL,
	[Original Ordered Qty] [float] NOT NULL,
	[Exch Rate Type] [varchar](3) NULL,
	[Supply-from Whs] [varchar](6) NULL,
	[So Shipment] [varchar](9) NULL,
	[Line Sequence] [int] NOT NULL,
	[Ship-to Whs] [varchar](6) NULL,
	[Ext Sales Rep] [varchar](9) NULL,
	[Return Reason] [varchar](6) NULL,
	[Sales Ord Type] [varchar](3) NULL,
	[Sales Price List] [varchar](3) NULL,
	[Installments] [int] NULL,
	[Ord Disc Amt] [float] NOT NULL,
	[Tax Classif] [varchar](12) NULL,
	[Delivery Terms] [varchar](3) NULL,
	[Discount Code] [varchar](3) NULL,
	[Carrier] [varchar](3) NULL,
	[Company number] [varchar](10) NOT NULL,
	[Sales Price Unit] [varchar](3) NULL,
	[Sales Qty Unit] [varchar](3) NULL,
	[Delivery Code] [varchar](6) NULL,
	[SO Discount] [float] NOT NULL,
	[Delivery Type] [int] NULL,
	[Items] [varchar](47) NULL,
	[Discount Amt] [float] NOT NULL,
	[Price Origin] [int] NULL,
	[PoTP] [varchar](9) NULL,
	[Line of Business] [varchar](6) NULL,
	[Payment Terms] [varchar](3) NULL,
	[Sales Rep] [varchar](9) NULL,
	[Financial Dept] [varchar](6) NULL,
	[Invoice-to Addr] [varchar](9) NULL,
	[Invoice-to BP] [varchar](9) NULL,
	[Sold-to Address] [varchar](9) NULL,
	[Sold-to BP] [varchar](9) NULL,
	[Payment Method] [varchar](3) NULL,
	[Rate Type] [varchar](3) NULL,
	[Currency] [varchar](3) NULL,
	[Service Office] [varchar](6) NULL,
	[Order Discount] [float] NULL,
	[Est Order Amt] [float] NOT NULL,
	[Ship-to Address] [varchar](9) NULL,
	[Ship-to BP] [varchar](9) NULL,
	[Sales Type] [varchar](6) NULL,
	[Tax Code] [varchar](9) NULL,
	[Department] [varchar](6) NULL,
	[Order Number] [varchar](9) NOT NULL,
	[Order Line Numb] [varchar](61) NULL,
	[Table Desc] [varchar](17) NOT NULL,
	[Table Shortcode] [varchar](5) NOT NULL,
	[Time of Action] [datetime] NULL,
	[SO Act Deliv Line Seq Numb] [int] NOT NULL,
	[SO Invoice Line] [int] NOT NULL,
	[Remain Order Qty] [float] NOT NULL,
	[Order Value Due] [float] NOT NULL,
	[Completed Delivery Flag] [int] NOT NULL,
	[Back Order Qty] [float] NOT NULL,
	[Ordered Qty] [float] NOT NULL,
	[DWH Load Time] [datetime] NOT NULL,
	[site] [varchar](9) NULL,
	[Delivered Value] [float] NOT NULL,
	[SO Order Status] [int] NULL,
	[SO Order Status Desc] [varchar](255) NULL,
	[Ship Constraint] [int] NULL,
	[Ship Constraint Desc] [varchar](255) NULL,
	[Carrier/LSP Desc] [varchar](255) NULL,
	[Deleted Record] [varchar](10) NULL,
	[Carrier Alpha Code] [varchar](20) NULL,
	[Buy-from Business Partner] [varchar](9) NULL,
	[Transport Category] [int] NULL,
	[Transport Category Desc] [varchar](255) NULL,
	[Change Reason Desc] [varchar](255) NULL,
	[Last Inventory Transaction Date] [datetime] NULL,
	[Inventory Allocated] [float] NULL,
	[Inventory Blocked] [float] NULL,
	[Inventory Blocked for Planning] [float] NULL,
	[Consignment Inventory Location Allocated] [float] NULL,
	[Consignment Inventory on Hand] [float] NULL,
	[Cumulative Issue] [float] NULL,
	[Consignment Inventory in Transit] [float] NULL,
	[Inventory Committed] [float] NULL,
	[Consignment on Order] [float] NULL,
	[Inventory Committed in Process] [float] NULL,
	[Consigned Quarantine] [float] NULL,
	[Goods in Transit] [float] NULL,
	[Historical Balance] [float] NULL,
	[Inventory on Hand] [float] NULL,
	[Company Owned Quarantine Inventory] [float] NULL,
	[Inventory in Transit] [float] NULL,
	[Inventory Location Allocated] [float] NULL,
	[Cust Owned Location Allocated] [float] NULL,
	[Cust Owned Blocked] [float] NULL,
	[Cust Owned Blocked for Planning] [float] NULL,
	[Cust Owned on Hand] [float] NULL,
	[Cust Owned in Transit] [float] NULL,
	[Cust Owned on Order] [float] NULL,
	[Cust Owned Quarantine] [float] NULL,
	[Comp Owned Location Allocated] [float] NULL,
	[Comp Owned on Order] [float] NULL,
	[Inventory on Order] [float] NULL,
	[Items Desc] [varchar](255) NULL,
	[Item Group] [varchar](6) NULL,
	[Product Class] [varchar](6) NULL,
	[Product Line] [varchar](6) NULL,
	[Item Signal] [varchar](3) NULL,
	[Country of Origin] [varchar](3) NULL,
	[Product Type] [varchar](3) NULL,
	[Inventory Unit] [varchar](3) NULL,
	[Serialized] [int] NULL,
	[Default Supply Source] [int] NULL,
	[Line of Business Desc] [varchar](255) NULL,
	[Sales Office Desc] [varchar](255) NULL,
	[Sales Order Type Desc] [varchar](255) NULL,
	[Ship-to Address Code] [varchar](9) NULL,
	[Ship-to Country] [varchar](50) NULL,
	[Ship-to Country Name] [varchar](100) NULL,
	[Ship-to BP Name] [varchar](255) NULL,
	[Ship-to State/Province] [varchar](3) NULL,
	[Ship-to City Name] [varchar](255) NULL,
	[Ship-to Latitude] [float] NULL,
	[Ship-to Longitude] [float] NULL,
	[Sold-to Address Code] [varchar](9) NULL,
	[Sold-to Country] [varchar](50) NULL,
	[Sold-to Country Name] [varchar](100) NULL,
	[Sold-to BP Name] [varchar](255) NULL,
	[Sold-to State/Province] [varchar](3) NULL,
	[Sold-to City Name] [varchar](255) NULL,
	[Sold-to Latitude] [float] NULL,
	[Sold-to Longitude] [float] NULL,
	[Tax Classification Desc] [varchar](255) NULL,
	[Max W/Tax %] [float] NULL,
	[SCT Allowed] [int] NULL,
	[SCT Allowed Falg] [varchar](255) NULL,
	[WIT Allowed] [int] NULL,
	[WIT Allowed Flag] [varchar](255) NULL,
	[Warehouse Desc] [varchar](255) NULL,
	[Warehouse Address Code] [varchar](9) NULL,
	[Financial Company] [int] NULL,
	[Enterprise unit of Wh] [varchar](6) NULL,
	[Inventory Mgt Business Partner] [varchar](9) NULL,
	[External Site] [int] NULL,
	[External Site Flag] [varchar](255) NULL,
	[Blocked for Inbound] [int] NULL,
	[Blocked for Inbound Desc] [varchar](255) NULL,
	[Blocked for Outbound] [int] NULL,
	[Blocked for Outbound Desc] [varchar](255) NULL,
	[Product Line Levels] [int] NULL,
	[Product Line First Level] [varchar](100) NULL,
	[Product Line Second Level] [varchar](100) NULL,
	[Product Line Third Level] [varchar](100) NULL,
	[Department Desc] [varchar](255) NULL,
	[Department Site] [varchar](9) NULL,
	[Department Type Key] [int] NULL,
	[Department Type] [varchar](255) NULL,
	[Ship-to Region] [varchar](50) NULL,
	[Ship-to Sub Region] [varchar](100) NULL,
	[Sold-to Region] [varchar](50) NULL,
	[Sold-to Sub Region] [varchar](100) NULL,
	[Default Supply Source By Site] [int] NULL,
	[Default Supply Source By Site Desc] [varchar](255) NULL,
	[Ship-to Address Desc] [varchar](255) NULL,
	[Sold-to Address Desc] [varchar](255) NULL,
	[SO Act Delivery Key] [varchar](255) NOT NULL,
	[row_no] [bigint] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [SO Act Delivery Key] )
)
GO

