/**********************************************************************************************************************
Table Name: [replncss].[fct Rep Production Receipts Cube]
Description: This Fact cube is created by joining the Fact Repetative Production Warehouse Receipts View & Dim Views which is exposed to the Tableau for Dashboard Build.

Data Type: Fact Data

Original Project: JBT Production Planning & Scheduling
Developer: Mohammed Majid
Date: 10/08/2021
Reviewed By: Atul Raje

Change History:N/A
**********************************************************************************************************************/

--DROP TABLE [replncss].[fct Rep Production Receipts Cube];

CREATE TABLE [replncss].[fct Rep Production Receipts Cube]
(
	[Activity] [varchar](255) NULL,
	[Actual Receipt Date] [date] NULL,
	[Customer Item Revision] [varchar](255) NULL,
	[Manufacturer] [varchar](6) NULL,
	[Complete] [int] NULL,
	[Complete Desc] [varchar](255) NULL,
	[Company number] [varchar](10) NOT NULL,
	[Confirmed] [int] NULL,
	[Confirmed Desc] [varchar](255) NULL,
	[Receiving Warehouse] [varchar](6) NULL,
	[Deleted] [varchar](10) NULL,
	[Direct Material Supply Execution] [int] NULL,
	[Direct Material Supply Execution Desc] [varchar](255) NULL,
	[Destination Location] [varchar](10) NULL,
	[Final Receipt] [int] NULL,
	[Final Receipt Desc] [varchar](255) NULL,
	[Inventory Date] [date] NULL,
	[Items] [varchar](47) NULL,
	[Line Status] [int] NULL,
	[Line Status Desc`] [varchar](255) NULL,
	[Order Origin] [int] NULL,
	[Order Origin Desc] [varchar](255) NULL,
	[Order Number] [varchar](9) NULL,
	[Operation Set] [int] NULL,
	[Order Line] [int] NULL,
	[Packing Slip] [varchar](255) NULL,
	[Packing Slip Qty in Receipt Unit] [float] NULL,
	[Packing Slip Qty] [float] NULL,
	[Packing Slip Unit] [varchar](3) NULL,
	[Inspection Qty] [float] NULL,
	[Advised Qty] [float] NULL,
	[Approved Qty] [float] NULL,
	[Destroyed Qty] [float] NULL,
	[Received Qty in Receipt Unit] [float] NULL,
	[Received Qty in Inv Unit] [float] NULL,
	[Rejected Qty] [float] NULL,
	[Scrapped Qty] [float] NULL,
	[Receipt Line] [int] NOT NULL,
	[Receipt Number] [varchar](9) NOT NULL,
	[Receipt Unit] [varchar](3) NULL,
	[Order Sequence] [int] NULL,
	[Ship-from BP] [varchar](9) NULL,
	[Shipping Date] [date] NULL,
	[Time of Action] [datetime] NULL,
	[Transaction Date] [date] NULL,
	[Receipt Line Text] [int] NULL,
	[DWH Load Time] [datetime] NOT NULL,
	[Carrier/LSP] [varchar](3) NULL,
	[Delivery Terms] [varchar](3) NULL,
	[Header Status] [int] NULL,
	[Header Status Desc] [varchar](255) NULL,
	[Inv Trans Type] [int] NULL,
	[Inv Trans Type Desc] [varchar](255) NULL,
	[Order Date] [date] NULL,
	[Ship-from Site] [varchar](9) NULL,
	[Ship-from Address] [varchar](9) NULL,
	[Ship-to Address] [varchar](9) NULL,
	[Office] [varchar](6) NULL,
	[Closed] [int] NULL,
	[Closed Desc] [varchar](255) NULL,
	[Work Center] [varchar](6) NULL,
	[Production Finish Date] [date] NULL,
	[Production Model] [varchar](9) NULL,
	[Production Start Date] [date] NULL,
	[Production Schedule] [varchar](9) NULL,
	[Ordered Qty] [float] NULL,
	[Schedule Type] [int] NULL,
	[Schedule Type Desc] [varchar](255) NULL,
	[Site] [varchar](9) NULL,
	[Prod Rec Fct Key] [varchar](50) NOT NULL,
	[Carrier/LSP Desc] [varchar](255) NULL,
	[Carrier Alpha Code] [varchar](20) NULL,
	[Buy-from Business Partner] [varchar](9) NULL,
	[Transport Category] [int] NULL,
	[Transport Category Desc] [varchar](255) NULL,
	[Last Inventory Transaction Date] [date] NULL,
	[Inventory Allocated] [float] NULL,
	[Inventory Blocked] [float] NULL,
	[Inventory Blocked for Planning] [float] NULL,
	[Consignment Inventory Location Allocated] [float] NULL,
	[Consignment Inventory on Hand] [float] NULL,
	[Cumulative Issue] [float] NULL,
	[Consignment Inventory in Transit] [float] NULL,
	[Inventory Committed] [float] NULL,
	[Consignment on Order] [float] NULL,
	[Inventory Committed in Process] [float] NULL,
	[Consigned Quarantine] [float] NULL,
	[Goods in Transit] [float] NULL,
	[Historical Balance] [float] NULL,
	[Inventory on Hand] [float] NULL,
	[Company Owned Quarantine Inventory] [float] NULL,
	[Inventory in Transit] [float] NULL,
	[Inventory Location Allocated] [float] NULL,
	[Cust Owned Location Allocated] [float] NULL,
	[Cust Owned Blocked] [float] NULL,
	[Cust Owned Blocked for Planning] [float] NULL,
	[Cust Owned on Hand] [float] NULL,
	[Cust Owned in Transit] [float] NULL,
	[Cust Owned on Order] [float] NULL,
	[Cust Owned Quarantine] [float] NULL,
	[Comp Owned Location Allocated] [float] NULL,
	[Comp Owned on Order] [float] NULL,
	[Inventory on Order] [float] NULL,
	[Items Desc] [varchar](255) NULL,
	[Item Group] [varchar](6) NULL,
	[Product Class] [varchar](6) NULL,
	[Product Line] [varchar](6) NULL,
	[Item Signal] [varchar](3) NULL,
	[Country of Origin] [varchar](3) NULL,
	[Product Type] [varchar](3) NULL,
	[Inventory Unit] [varchar](3) NULL,
	[Serialized] [int] NULL,
	[Default Supply Source] [int] NULL,
	[Ship-from Address Code] [varchar](9) NULL,
	[Ship-from Country] [varchar](50) NULL,
	[Ship-from Country Name] [varchar](255) NULL,
	[Ship-from BP Name] [varchar](255) NULL,
	[Ship-from State/Province] [varchar](50) NULL,
	[Ship-from City Name] [varchar](255) NULL,
	[Warehouse Desc] [varchar](255) NULL,
	[Warehouse Address Code] [varchar](9) NULL,
	[Financial Company] [int] NULL,
	[Enterprise unit of Wh] [varchar](6) NULL,
	[Inventory Mgt Business Partner] [varchar](9) NULL,
	[External Site] [int] NULL,
	[External Site Flag] [varchar](255) NULL,
	[Ship-from Region] [varchar](50) NULL,
	[Ship-from Sub Region] [varchar](100) NULL,
	[Ship-from Address Desc] [varchar](255) NULL,
	[Ship-to Address Desc] [varchar](255) NULL,
	[Product Line Levels] [int] NULL,
	[Product Line First Level] [varchar](255) NULL,
	[Product Line Second Level] [varchar](255) NULL,
	[Product Line Third Level] [varchar](255) NULL,
	[Actual Receipt Datetime] [datetime] NULL,
	[Actual Receipt Datetime EST] [datetime] NULL,
	[Actual Receipt Date EST] [date] NULL
)
WITH
(
	DISTRIBUTION = HASH ( [Prod Rec Fct Key] )
)
GO


