name: CI

on:
  push:
    branches:
    - main

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az, dbatools
      - uses: actions/checkout@v1
      - name: Run script
        shell: pwsh
        run: .\Script.ps1 -host_name "synw-jbt-dw-dev1"
    
