name: CI

on:
  push:
    branches:
     - '!main'
  
jobs:
  install-dependencies:
    name: Install dependency\ies and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Read release path location
        id: release_path
        shell: pwsh
        run: |
            $file_text= Get-Content "./DeploymentScript/Release.txt"
            echo "::set-output name=new_value::$file_text"
      - name: copy release management scripts
        run: Copy './DeploymentScript' '${github.workspace}'
        shell: pwsh
      - name: publish artifact  deployment script
        uses: actions/upload-artifact@v2
        with:
         path: '${{ github.workspace }}/DeploymentScript'
         name: DeploymentScript
      - name: publish artifact release files
        uses: actions/upload-artifact@v2
        with:
         path: '${{ github.workspace }}/${{steps.release_path.outputs.new_value}}'   
         name: ReleaseFiles 
      - uses: Azure/login@v1
        with:
          creds: '{"clientId": ${{ secrets.CLIENT_ID }},"clientSecret": ${{ secrets.CLIENT_SECRET }},"tenantId": ${{ secrets.TENANT_ID }}}'
          allow-no-subscriptions: true
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "JbtDevopsKey"
          secrets: 'Hostname'
        id: myGetSecretAction
      - uses: actions/checkout@v1
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az, dbatools
      - uses: actions/checkout@v1
      - name: Run script
        shell: pwsh
        run: |
            .\DeploymentScript\Script.ps1 -host_name ${{steps.myGetSecretAction.outputs.Hostname}} -release_path ${{steps.release_path.outputs.new_value}}
              
    
