name: CI

on:
  push:
    branches:
    - main

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "JbtDevopsKey"
          secrets: 'Hostname'
        id: myGetSecretAction
      - uses: actions/checkout@v1
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az, dbatools
      - uses: actions/checkout@v1
      - name: Run script
        shell: pwsh
        run: .\Script.ps1 -host_name ${{steps.myGetSecretAction.outputs.Hostname}}
    
