name: CI

on:
  push:
    branches:
    - main

jobs:
  install-dependencies:
    name: Install dependency and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy release management scripts
        run: Copy './' '${github.workspace}'
        shell: pwsh
      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
         path: ${{ github.workspace }}
          
      - uses: Azure/login@v1
        with:
          creds: '{"clientId": ${{ secrets.CLIENT_ID }},"clientSecret": ${{ secrets.CLIENT_SECRET }},"tenantId": ${{ secrets.TENANT_ID }}}'
          allow-no-subscriptions: true
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "JbtDevopsKey"
          secrets: 'Hostname, DBName, Username, Password'
        id: myGetSecretAction
      - uses: actions/checkout@v1
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az, dbatools
      - uses: actions/checkout@v1
      - name: Run script
        shell: pwsh
        run: |
            .\Script.ps1 -host_name ${{steps.myGetSecretAction.outputs.Hostname}}\
            -db_name ${{steps.myGetSecretAction.outputs.DBName}}\
            -user_name ${{steps.myGetSecretAction.outputs.Username}}\
            -user_pwd '${{steps.myGetSecretAction.outputs.Password}}'
              
    
